{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-models",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-models-6.0.1.4-beta.jar",
          "url": "mdlive-models-6.0.1.4-beta.jar",
          "size": 2410957,
          "sha512": "331e83fb30c09f05a956f847945735b4f9fd3f0664a3a90034f95cfeae9a48c932f9ed516559b0b77c2fd44425dab9a989dbecf612661114b3302c14b033f810",
          "sha256": "c03010587cbe93f075b3b246775b392cfdb8bd99c077ab595d064c3d82f717c8",
          "sha1": "e50618d209acab3df2920b4ebf751c570fd535dc",
          "md5": "30ea05e59e2fdd7711ab77f6a70e864b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-models-6.0.1.4-beta.jar",
          "url": "mdlive-models-6.0.1.4-beta.jar",
          "size": 2410957,
          "sha512": "331e83fb30c09f05a956f847945735b4f9fd3f0664a3a90034f95cfeae9a48c932f9ed516559b0b77c2fd44425dab9a989dbecf612661114b3302c14b033f810",
          "sha256": "c03010587cbe93f075b3b246775b392cfdb8bd99c077ab595d064c3d82f717c8",
          "sha1": "e50618d209acab3df2920b4ebf751c570fd535dc",
          "md5": "30ea05e59e2fdd7711ab77f6a70e864b"
        }
      ]
    }
  ]
}
