{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.0.1.3-beta.jar",
          "url": "feature-dashboard-domain-6.0.1.3-beta.jar",
          "size": 153368,
          "sha512": "22bd564c5ef2eb99235ac910b4d0c8dfbb578abd7618aa551ef052aa9f62884f2e27b2e458fa6661e62318486bf1608de92f5d3e8c97a981445cc8596ae160b7",
          "sha256": "51433744cd763b96a0a047a1695c9bed884a3c042873581bcf23262702c4178b",
          "sha1": "848c2bb2205275de6bca54d668ac35e65f407c4c",
          "md5": "b59ab340bb04f7bdb064201d2a9a9019"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.0.1.3-beta.jar",
          "url": "feature-dashboard-domain-6.0.1.3-beta.jar",
          "size": 153368,
          "sha512": "22bd564c5ef2eb99235ac910b4d0c8dfbb578abd7618aa551ef052aa9f62884f2e27b2e458fa6661e62318486bf1608de92f5d3e8c97a981445cc8596ae160b7",
          "sha256": "51433744cd763b96a0a047a1695c9bed884a3c042873581bcf23262702c4178b",
          "sha1": "848c2bb2205275de6bca54d668ac35e65f407c4c",
          "md5": "b59ab340bb04f7bdb064201d2a9a9019"
        }
      ]
    }
  ]
}
