{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk-common-android-sdk-common",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-common-android-sdk-common-6.0.1.4-beta.aar",
          "url": "android-sdk-common-android-sdk-common-6.0.1.4-beta.aar",
          "size": 17998,
          "sha512": "66c42f19d3b6f7df9bd39dcdc835d035067bf982dc3a2356d9bf24682b26e5863dbd20ca497e3e33b57650c5c1ab02aaa12cf149c7fac3bb5b12e6923851baca",
          "sha256": "626720a895c077eb5031c7a68aab3bde06b5f86104a9316d461d517b4bb1760d",
          "sha1": "d6aad7b7df3babff7611006151cbadd9423d9487",
          "md5": "3837717096b1b440d8b32efef90d9d4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-common-android-sdk-common-6.0.1.4-beta.aar",
          "url": "android-sdk-common-android-sdk-common-6.0.1.4-beta.aar",
          "size": 17998,
          "sha512": "66c42f19d3b6f7df9bd39dcdc835d035067bf982dc3a2356d9bf24682b26e5863dbd20ca497e3e33b57650c5c1ab02aaa12cf149c7fac3bb5b12e6923851baca",
          "sha256": "626720a895c077eb5031c7a68aab3bde06b5f86104a9316d461d517b4bb1760d",
          "sha1": "d6aad7b7df3babff7611006151cbadd9423d9487",
          "md5": "3837717096b1b440d8b32efef90d9d4d"
        }
      ]
    }
  ]
}
