{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.1.0.4-beta.jar",
          "url": "mdlive-common-6.1.0.4-beta.jar",
          "size": 15538,
          "sha512": "3d9a15708957c69fafd96b1895eb6ca4c9ff8362355d12c1da1691adba2ec92789689a7b0f4e0f0785d48c7e5898e53a4acac5ac4739c8be96e446b6ceab728a",
          "sha256": "c6734bebe9dd5808807bf635bd4a1fe3f60980342a936caa03ed5d8d61ef0704",
          "sha1": "c72508e6e6a56e7953bb9fc981c533dbb5482fd6",
          "md5": "99c36d15884b808cd5338dea85365157"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.1.0.4-beta.jar",
          "url": "mdlive-common-6.1.0.4-beta.jar",
          "size": 15538,
          "sha512": "3d9a15708957c69fafd96b1895eb6ca4c9ff8362355d12c1da1691adba2ec92789689a7b0f4e0f0785d48c7e5898e53a4acac5ac4739c8be96e446b6ceab728a",
          "sha256": "c6734bebe9dd5808807bf635bd4a1fe3f60980342a936caa03ed5d8d61ef0704",
          "sha1": "c72508e6e6a56e7953bb9fc981c533dbb5482fd6",
          "md5": "99c36d15884b808cd5338dea85365157"
        }
      ]
    }
  ]
}
