{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.1-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.1-beta.jar",
          "size": 12835,
          "sha512": "a628d67b8f3d10cf5693ee2c833661776bfb24e801fefbe3da6c1e010f712674f1c87b947e57423d702c98d26482f5dd6c492beca6c5cdbce650d1d69c1fec17",
          "sha256": "c24d16469d34ea47bdeb2aa83b65989dbf8b3a3ac0983a73ac3d7333cd3e3da7",
          "sha1": "3cf547865e05a542b2018a1207c1183f9a9f700a",
          "md5": "c555ebfc1babf6dae69bd369e0b995a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.1-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.1-beta.jar",
          "size": 12835,
          "sha512": "a628d67b8f3d10cf5693ee2c833661776bfb24e801fefbe3da6c1e010f712674f1c87b947e57423d702c98d26482f5dd6c492beca6c5cdbce650d1d69c1fec17",
          "sha256": "c24d16469d34ea47bdeb2aa83b65989dbf8b3a3ac0983a73ac3d7333cd3e3da7",
          "sha1": "3cf547865e05a542b2018a1207c1183f9a9f700a",
          "md5": "c555ebfc1babf6dae69bd369e0b995a2"
        }
      ]
    }
  ]
}
