{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-domain-6.3.0-alpha.jar",
          "url": "feature-domain-6.3.0-alpha.jar",
          "size": 24468,
          "sha512": "1518b7c32a4044c6b17bbf6544322a46800c6654f069147b558ae7b7a36ab202a212e5e20ca955ec853f3f0db9bc9ace613193abefedb38598168137f4a5d96f",
          "sha256": "11edabdca068166019327fce96151a9bb494ad511505b6c944a67480724144eb",
          "sha1": "961cc46c6db47660048d3b6ccc443a764aa342f8",
          "md5": "e3bd2c0dda36d626832f13fab1e9b1b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-domain-6.3.0-alpha.jar",
          "url": "feature-domain-6.3.0-alpha.jar",
          "size": 24468,
          "sha512": "1518b7c32a4044c6b17bbf6544322a46800c6654f069147b558ae7b7a36ab202a212e5e20ca955ec853f3f0db9bc9ace613193abefedb38598168137f4a5d96f",
          "sha256": "11edabdca068166019327fce96151a9bb494ad511505b6c944a67480724144eb",
          "sha1": "961cc46c6db47660048d3b6ccc443a764aa342f8",
          "md5": "e3bd2c0dda36d626832f13fab1e9b1b5"
        }
      ]
    }
  ]
}
