{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.0.1.4-beta.jar",
          "url": "mdlive-services-6.0.1.4-beta.jar",
          "size": 928090,
          "sha512": "e972935f98d68a7c71669d569e5206cc63a326f60b398d88c2a63f97e6bc3520d827644798874ed44ada79e7eca7f182b581e3f7d1820b3641bb563e7fd9aacb",
          "sha256": "f568fd0333892c52a4dc737a6afcc1482286681b503987b16ca2c3bf7b7a66f0",
          "sha1": "c77b32082e74783d0226596178470f8accd0c0b7",
          "md5": "b56146cbd620af753728f7884fdf36aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.0.1.4-beta.jar",
          "url": "mdlive-services-6.0.1.4-beta.jar",
          "size": 928090,
          "sha512": "e972935f98d68a7c71669d569e5206cc63a326f60b398d88c2a63f97e6bc3520d827644798874ed44ada79e7eca7f182b581e3f7d1820b3641bb563e7fd9aacb",
          "sha256": "f568fd0333892c52a4dc737a6afcc1482286681b503987b16ca2c3bf7b7a66f0",
          "sha1": "c77b32082e74783d0226596178470f8accd0c0b7",
          "md5": "b56146cbd620af753728f7884fdf36aa"
        }
      ]
    }
  ]
}
