{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.1.0.5-beta.jar",
          "url": "mdlive-services-6.1.0.5-beta.jar",
          "size": 936590,
          "sha512": "70c0dce69e76888535212b25e0c2863149557535446a143b8214d0551fe9d6d8edeb337b1751d1da1a007e0907b5dc7e4aa329a6a188298bf6c98bdba7f37f08",
          "sha256": "c06e17e41b447ea2a557556284fa6ff3def3137ac916322fccc91bc85f4e8952",
          "sha1": "0dd8750bd49038150e6505b449ab691b4373b1a8",
          "md5": "0779157192b4bc4936a749c0aa5cb4c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.1.0.5-beta.jar",
          "url": "mdlive-services-6.1.0.5-beta.jar",
          "size": 936590,
          "sha512": "70c0dce69e76888535212b25e0c2863149557535446a143b8214d0551fe9d6d8edeb337b1751d1da1a007e0907b5dc7e4aa329a6a188298bf6c98bdba7f37f08",
          "sha256": "c06e17e41b447ea2a557556284fa6ff3def3137ac916322fccc91bc85f4e8952",
          "sha1": "0dd8750bd49038150e6505b449ab691b4373b1a8",
          "md5": "0779157192b4bc4936a749c0aa5cb4c2"
        }
      ]
    }
  ]
}
