{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.0.1.4-beta.jar",
          "url": "mdlive-common-6.0.1.4-beta.jar",
          "size": 15516,
          "sha512": "23433a48e1b5d7f9b879bbf2b643eee920d271d1dc8d4fb9516ae81db632905e90bacd98ff18b7b2e802649cabb0594009dc4e033cf773e69b0ba63418f69bc7",
          "sha256": "f159e727c223d6a5a6173eef9f1bbd66e47460b9c3b5010db66d2e94c76bad3f",
          "sha1": "5f314c95d351831fefb3966cadbae42ad939b56a",
          "md5": "c7704689523d39c5f023ca9395b90033"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.0.1.4-beta.jar",
          "url": "mdlive-common-6.0.1.4-beta.jar",
          "size": 15516,
          "sha512": "23433a48e1b5d7f9b879bbf2b643eee920d271d1dc8d4fb9516ae81db632905e90bacd98ff18b7b2e802649cabb0594009dc4e033cf773e69b0ba63418f69bc7",
          "sha256": "f159e727c223d6a5a6173eef9f1bbd66e47460b9c3b5010db66d2e94c76bad3f",
          "sha1": "5f314c95d351831fefb3966cadbae42ad939b56a",
          "md5": "c7704689523d39c5f023ca9395b90033"
        }
      ]
    }
  ]
}
