{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk-java-android-sdk-java",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.0.1.4-beta.jar",
          "url": "android-sdk-java-android-sdk-java-6.0.1.4-beta.jar",
          "size": 87574,
          "sha512": "58c1472781b681f33b486ebb782ee25479d1afc3e5f4824ece34b74f09d6b4a10710a4ca5498fa0c574d66829bec4a298552ff56dbd40196496e028400120cd7",
          "sha256": "98d81750c96097266c536f744ff8e277c7a733763e6d127e46b707da175f1243",
          "sha1": "23febb228427060371a42549cf730b7376a19958",
          "md5": "629585deae8e84e173233badb9953c77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.0.1.4-beta.jar",
          "url": "android-sdk-java-android-sdk-java-6.0.1.4-beta.jar",
          "size": 87574,
          "sha512": "58c1472781b681f33b486ebb782ee25479d1afc3e5f4824ece34b74f09d6b4a10710a4ca5498fa0c574d66829bec4a298552ff56dbd40196496e028400120cd7",
          "sha256": "98d81750c96097266c536f744ff8e277c7a733763e6d127e46b707da175f1243",
          "sha1": "23febb228427060371a42549cf730b7376a19958",
          "md5": "629585deae8e84e173233badb9953c77"
        }
      ]
    }
  ]
}
