{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.1.0.1-beta.jar",
          "url": "mdlive-services-6.1.0.1-beta.jar",
          "size": 935803,
          "sha512": "ca63be2ff4c11348f20c7df769ca324d983d68217a543e7a7e260e66cd8f4da3c8bc536516d0ba1f7add458230d5a10f225b8909d0eec0eee908e8f19811821e",
          "sha256": "5900c98806b34026d6e93d34375a507ed17e6a64da67b98be66bcbc24972c586",
          "sha1": "703f24dbce96856b2f6f129efe76c04e363f9988",
          "md5": "97c0e77fe07b5647e6c32019496a4a5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.1.0.1-beta.jar",
          "url": "mdlive-services-6.1.0.1-beta.jar",
          "size": 935803,
          "sha512": "ca63be2ff4c11348f20c7df769ca324d983d68217a543e7a7e260e66cd8f4da3c8bc536516d0ba1f7add458230d5a10f225b8909d0eec0eee908e8f19811821e",
          "sha256": "5900c98806b34026d6e93d34375a507ed17e6a64da67b98be66bcbc24972c586",
          "sha1": "703f24dbce96856b2f6f129efe76c04e363f9988",
          "md5": "97c0e77fe07b5647e6c32019496a4a5a"
        }
      ]
    }
  ]
}
