{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-ui",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.1.0.2-beta.aar",
          "url": "mdlive-ui-6.1.0.2-beta.aar",
          "size": 3036386,
          "sha512": "ab7fba6f33bdfa3d112f3e3ab05d89f9b889160a0c93988ee099ed4b40de6b03b4e4dc712b23a353e1275dfa649744ede218b719b24893c35c6b02fbc9e4b155",
          "sha256": "3a76a1e69d10e79aba5d9bae21d9bd74fe4daea941c7961d53046a324a281025",
          "sha1": "a3ce8cb823953514f09762f0f7a654c9eb95d682",
          "md5": "e6b86802f70fd47b1b40ce912f702ddb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.1.0.2-beta.aar",
          "url": "mdlive-ui-6.1.0.2-beta.aar",
          "size": 3036386,
          "sha512": "ab7fba6f33bdfa3d112f3e3ab05d89f9b889160a0c93988ee099ed4b40de6b03b4e4dc712b23a353e1275dfa649744ede218b719b24893c35c6b02fbc9e4b155",
          "sha256": "3a76a1e69d10e79aba5d9bae21d9bd74fe4daea941c7961d53046a324a281025",
          "sha1": "a3ce8cb823953514f09762f0f7a654c9eb95d682",
          "md5": "e6b86802f70fd47b1b40ce912f702ddb"
        }
      ]
    }
  ]
}
