{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-testing",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-testing-6.3.0-alpha.jar",
          "url": "mdlive-testing-6.3.0-alpha.jar",
          "size": 8104,
          "sha512": "dbafe3ae4ab4c6a182c2ee7675c7454a9d03ebc9354a4cc85803256732b07f915e319242da7461df3cde9d0ca7673d4156386a9e6cc811b38fa90c8186f8b268",
          "sha256": "bf92374d8dced449b3bb0bd5117febdfa7c1ae51320bfb8c515b2b8e255faaed",
          "sha1": "1f97b836bc9b5c46f0ddb5aacf20efbbb9f66bc1",
          "md5": "4039eebc1202e7e130c31fb84bc0939b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-testing-6.3.0-alpha.jar",
          "url": "mdlive-testing-6.3.0-alpha.jar",
          "size": 8104,
          "sha512": "dbafe3ae4ab4c6a182c2ee7675c7454a9d03ebc9354a4cc85803256732b07f915e319242da7461df3cde9d0ca7673d4156386a9e6cc811b38fa90c8186f8b268",
          "sha256": "bf92374d8dced449b3bb0bd5117febdfa7c1ae51320bfb8c515b2b8e255faaed",
          "sha1": "1f97b836bc9b5c46f0ddb5aacf20efbbb9f66bc1",
          "md5": "4039eebc1202e7e130c31fb84bc0939b"
        }
      ]
    }
  ]
}
