{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-core",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-6.1.0.4-beta.aar",
          "url": "mdlive-core-6.1.0.4-beta.aar",
          "size": 105931,
          "sha512": "1d3e6132df1aedc63386f6b88e2b7fc513f0c0b900fa6db5b8f7d67c872037661b6f385876b451c2e78d1ddd85ff0591fa8da83b0628de0d95fb6632aa86c873",
          "sha256": "7238351c8cd4fad5ac0fd3316d6b8d6e5b026325defcd740579fd75140605854",
          "sha1": "48ff81cd1d15bc0d4360dda9fe814f2f68ecc64d",
          "md5": "b5e6dd11c53341e30837af3565d975ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-ui",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-data",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-ui",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-data",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-labs-ui",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-labs-data",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-labs-domain",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.45"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-6.1.0.4-beta.aar",
          "url": "mdlive-core-6.1.0.4-beta.aar",
          "size": 105931,
          "sha512": "1d3e6132df1aedc63386f6b88e2b7fc513f0c0b900fa6db5b8f7d67c872037661b6f385876b451c2e78d1ddd85ff0591fa8da83b0628de0d95fb6632aa86c873",
          "sha256": "7238351c8cd4fad5ac0fd3316d6b8d6e5b026325defcd740579fd75140605854",
          "sha1": "48ff81cd1d15bc0d4360dda9fe814f2f68ecc64d",
          "md5": "b5e6dd11c53341e30837af3565d975ee"
        }
      ]
    }
  ]
}
