{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.0.1.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.0.1.1-beta.jar",
          "url": "feature-dashboard-domain-6.0.1.1-beta.jar",
          "size": 153368,
          "sha512": "1dbe3059fe9143e0184fe768c9347f7163c1ec460d279f72002de090d7fbac81da053f8189d85ab89cbb30eac9c97d0c7adc408d9f791272e4a4e8539db3abaa",
          "sha256": "f09c62347741380d5069b4648502a5b86a698755172035fd6f8162fe09f2b41b",
          "sha1": "6e2faebcded1295e050f49a270bc5fa9020699f9",
          "md5": "65b588e71852c736ddba944da99a8204"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.0.1.1-beta.jar",
          "url": "feature-dashboard-domain-6.0.1.1-beta.jar",
          "size": 153368,
          "sha512": "1dbe3059fe9143e0184fe768c9347f7163c1ec460d279f72002de090d7fbac81da053f8189d85ab89cbb30eac9c97d0c7adc408d9f791272e4a4e8539db3abaa",
          "sha256": "f09c62347741380d5069b4648502a5b86a698755172035fd6f8162fe09f2b41b",
          "sha1": "6e2faebcded1295e050f49a270bc5fa9020699f9",
          "md5": "65b588e71852c736ddba944da99a8204"
        }
      ]
    }
  ]
}
