{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-6.1.0.4-beta.aar",
          "url": "android-sdk-6.1.0.4-beta.aar",
          "size": 26787,
          "sha512": "84c74074aa37ac128f23d59e9ae7ff3aab6230c259083d1ea44b8976363078ad2b0890a5ed9c364207057b50c93ea168f37ccb9dbb15ad2cca5c2e3370601e6c",
          "sha256": "5bbb9b8582165f22a060ffb51cf7a73d4f41eb328a1464b6aa09755f16515c2b",
          "sha1": "879909f77a4487b3bd9ca3c30c5228fd0cbe2a58",
          "md5": "ff116bfc1288a9046cd2b3490e16ab09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-common",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-core",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-6.1.0.4-beta.aar",
          "url": "android-sdk-6.1.0.4-beta.aar",
          "size": 26787,
          "sha512": "84c74074aa37ac128f23d59e9ae7ff3aab6230c259083d1ea44b8976363078ad2b0890a5ed9c364207057b50c93ea168f37ccb9dbb15ad2cca5c2e3370601e6c",
          "sha256": "5bbb9b8582165f22a060ffb51cf7a73d4f41eb328a1464b6aa09755f16515c2b",
          "sha1": "879909f77a4487b3bd9ca3c30c5228fd0cbe2a58",
          "md5": "ff116bfc1288a9046cd2b3490e16ab09"
        }
      ]
    }
  ]
}
