{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-pharmacy-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-pharmacy-domain-6.3.0-alpha.jar",
          "url": "feature-pharmacy-domain-6.3.0-alpha.jar",
          "size": 23761,
          "sha512": "920188d41000a18bc20d793c3a82c285cb7078d8503459020e71ce528fe9b7cee4348a2f21e4de0390dbb1d45cdd6c1a6829ad5fe89018a57ea9fbb8020ec773",
          "sha256": "ad263fd3092fabf26ae588218208c2ce34717188fe9dc513b82fbec06710cfa6",
          "sha1": "8e946783a280cbdd6847e58da5f4aff3ab822f41",
          "md5": "dbb945689623c4f3fcb751e59be0d501"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-pharmacy-domain-6.3.0-alpha.jar",
          "url": "feature-pharmacy-domain-6.3.0-alpha.jar",
          "size": 23761,
          "sha512": "920188d41000a18bc20d793c3a82c285cb7078d8503459020e71ce528fe9b7cee4348a2f21e4de0390dbb1d45cdd6c1a6829ad5fe89018a57ea9fbb8020ec773",
          "sha256": "ad263fd3092fabf26ae588218208c2ce34717188fe9dc513b82fbec06710cfa6",
          "sha1": "8e946783a280cbdd6847e58da5f4aff3ab822f41",
          "md5": "dbb945689623c4f3fcb751e59be0d501"
        }
      ]
    }
  ]
}
