{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-labs-data",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-data-6.1.0.2-beta.aar",
          "url": "feature-labs-data-6.1.0.2-beta.aar",
          "size": 32097,
          "sha512": "d3d71bed78ff7e43f6320149a020e476103566d74202b82b6255f7d94ccd1ed8e2ec635d96438b7d437200ad5f87be233c6af1d9141ec9778f78cb064513f554",
          "sha256": "fa1c4471f184ba7401b7eaeab3a849b368483aea444afad3c3d418d69b4f7f06",
          "sha1": "91ac3efa91c0a3feae575081c66c685f229afd86",
          "md5": "007a0b99d92a3c2addb8c9a3a0768253"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-labs-domain",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-data-6.1.0.2-beta.aar",
          "url": "feature-labs-data-6.1.0.2-beta.aar",
          "size": 32097,
          "sha512": "d3d71bed78ff7e43f6320149a020e476103566d74202b82b6255f7d94ccd1ed8e2ec635d96438b7d437200ad5f87be233c6af1d9141ec9778f78cb064513f554",
          "sha256": "fa1c4471f184ba7401b7eaeab3a849b368483aea444afad3c3d418d69b4f7f06",
          "sha1": "91ac3efa91c0a3feae575081c66c685f229afd86",
          "md5": "007a0b99d92a3c2addb8c9a3a0768253"
        }
      ]
    }
  ]
}
