{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-data",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-data-6.0.1.3-beta.aar",
          "url": "feature-debugmenu-data-6.0.1.3-beta.aar",
          "size": 9011,
          "sha512": "413e1e277c5bdc4285b8c056ae15b1b664554483fd3f5f4c426fb1846118d6e17e71531f83048f50ef581cb97a49dbef5d9b700483a015e1a59b927f7a05f893",
          "sha256": "29425e6f1054186d092d399c7fe27e58a719878d0ba491a3bf988980462095d2",
          "sha1": "eeb46df464114b202c823d048d669a9fcf0a6e02",
          "md5": "6930224ab9f501c78b68168b1b7f4792"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.45"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-data-6.0.1.3-beta.aar",
          "url": "feature-debugmenu-data-6.0.1.3-beta.aar",
          "size": 9011,
          "sha512": "413e1e277c5bdc4285b8c056ae15b1b664554483fd3f5f4c426fb1846118d6e17e71531f83048f50ef581cb97a49dbef5d9b700483a015e1a59b927f7a05f893",
          "sha256": "29425e6f1054186d092d399c7fe27e58a719878d0ba491a3bf988980462095d2",
          "sha1": "eeb46df464114b202c823d048d669a9fcf0a6e02",
          "md5": "6930224ab9f501c78b68168b1b7f4792"
        }
      ]
    }
  ]
}
