{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.0-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.0-beta.jar",
          "size": 208128,
          "sha512": "77ac095529384a47fcef2a5f58bc0193c54cc8fe3ad1c2fc7066bdc9624b1aaec52f73537b5977447618d454f7ba76c8749c0d366aca98d27149e9d8b7756e34",
          "sha256": "5435971398c2018d43d7640d7d9e9f23ce7c9a240e219b29cdcbe9d53aabd5a8",
          "sha1": "ad978fa0c43628240235080061e8b93aeb6ab45e",
          "md5": "9416852ecf8f2724c17d898ab6a27c85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.0-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.0-beta.jar",
          "size": 208128,
          "sha512": "77ac095529384a47fcef2a5f58bc0193c54cc8fe3ad1c2fc7066bdc9624b1aaec52f73537b5977447618d454f7ba76c8749c0d366aca98d27149e9d8b7756e34",
          "sha256": "5435971398c2018d43d7640d7d9e9f23ce7c9a240e219b29cdcbe9d53aabd5a8",
          "sha1": "ad978fa0c43628240235080061e8b93aeb6ab45e",
          "md5": "9416852ecf8f2724c17d898ab6a27c85"
        }
      ]
    }
  ]
}
