{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-labs-domain",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-domain-6.1.0.4-beta.jar",
          "url": "feature-labs-domain-6.1.0.4-beta.jar",
          "size": 24142,
          "sha512": "bca95bd0f71d8c40783ebea8a8d12e2ba8c4cbd8366733cf3c437c61c2b3ffb3b8b39064a90e324af703cd8bf2409dae20115a92b8b3501c754f6e6d39237704",
          "sha256": "612bfb37bc9dc5df381c0da73a72800ba62a7ebb4be0a36432f4ab73ddd8cb93",
          "sha1": "13caa416dfe8f5c19cc60bdb12eab19e663e5ed9",
          "md5": "5436711bf02e6e99d48506744aba088a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-domain-6.1.0.4-beta.jar",
          "url": "feature-labs-domain-6.1.0.4-beta.jar",
          "size": 24142,
          "sha512": "bca95bd0f71d8c40783ebea8a8d12e2ba8c4cbd8366733cf3c437c61c2b3ffb3b8b39064a90e324af703cd8bf2409dae20115a92b8b3501c754f6e6d39237704",
          "sha256": "612bfb37bc9dc5df381c0da73a72800ba62a7ebb4be0a36432f4ab73ddd8cb93",
          "sha1": "13caa416dfe8f5c19cc60bdb12eab19e663e5ed9",
          "md5": "5436711bf02e6e99d48506744aba088a"
        }
      ]
    }
  ]
}
