{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-testing",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-testing-6.1.0.4-beta.jar",
          "url": "mdlive-testing-6.1.0.4-beta.jar",
          "size": 8123,
          "sha512": "abecca76d6c5455f9c3c0513026daba616fe85be946c579b75c7852ba6d10f177ad4dc3840bd3a3845b0a5912a36cc8e3eaaa4cca6bd85a0b526e8af3298896c",
          "sha256": "65ce3285e2e9ab6f39c38665edb558917eba3735e48eb1fe68aae834bee08a2d",
          "sha1": "ab1fbd7e5dc26a159440ff9380f410e0855630dc",
          "md5": "ff3d2f14bfaf81f5166bf39c5c804bb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-testing-6.1.0.4-beta.jar",
          "url": "mdlive-testing-6.1.0.4-beta.jar",
          "size": 8123,
          "sha512": "abecca76d6c5455f9c3c0513026daba616fe85be946c579b75c7852ba6d10f177ad4dc3840bd3a3845b0a5912a36cc8e3eaaa4cca6bd85a0b526e8af3298896c",
          "sha256": "65ce3285e2e9ab6f39c38665edb558917eba3735e48eb1fe68aae834bee08a2d",
          "sha1": "ab1fbd7e5dc26a159440ff9380f410e0855630dc",
          "md5": "ff3d2f14bfaf81f5166bf39c5c804bb8"
        }
      ]
    }
  ]
}
