{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-ui",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-ui-6.1.0.0-beta.aar",
          "url": "feature-debugmenu-ui-6.1.0.0-beta.aar",
          "size": 537595,
          "sha512": "1e36073e76d1e0b0555afe84f08e0da85143349e59b3dce8bdac59ff476a3790da53942ba8a547aa8dd4144d069271be04cd6acf6bbcf6b92bf19dc774ce5c4c",
          "sha256": "938862808529a0885dd03505bcbb068fc8880a0a5fc650a7d905268ed3076b84",
          "sha1": "5f8335e5a88fba1e716b9cace5c40b2bf292231e",
          "md5": "5989b2166fa8763064a4ab2c1b2463e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-data",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "MDLive.feature-labs",
          "module": "ui",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-ui",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "MDLive.feature-labs",
          "module": "domain",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-ui-6.1.0.0-beta.aar",
          "url": "feature-debugmenu-ui-6.1.0.0-beta.aar",
          "size": 537595,
          "sha512": "1e36073e76d1e0b0555afe84f08e0da85143349e59b3dce8bdac59ff476a3790da53942ba8a547aa8dd4144d069271be04cd6acf6bbcf6b92bf19dc774ce5c4c",
          "sha256": "938862808529a0885dd03505bcbb068fc8880a0a5fc650a7d905268ed3076b84",
          "sha1": "5f8335e5a88fba1e716b9cace5c40b2bf292231e",
          "md5": "5989b2166fa8763064a4ab2c1b2463e3"
        }
      ]
    }
  ]
}
