{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-template-data",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-data-6.3.0-alpha.aar",
          "url": "feature-template-data-6.3.0-alpha.aar",
          "size": 2453,
          "sha512": "49a823f4375035d166ced2a2f1405899515a2f0eb3961819400e9e0bcb8eb4f233144554b9789c1f3e1068f18d0a1e95dd0d398c34293d8e5f8cc1d8eb1c5815",
          "sha256": "dfd4ab56d2e25b6ce3b26e6789351190b16e3a5d129efa21d2f9926a948144cf",
          "sha1": "0c08d99acc17d0e2328ea20461839664d568c726",
          "md5": "52b875ee5418cf90aca4788aebcd459b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-template-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-data-6.3.0-alpha.aar",
          "url": "feature-template-data-6.3.0-alpha.aar",
          "size": 2453,
          "sha512": "49a823f4375035d166ced2a2f1405899515a2f0eb3961819400e9e0bcb8eb4f233144554b9789c1f3e1068f18d0a1e95dd0d398c34293d8e5f8cc1d8eb1c5815",
          "sha256": "dfd4ab56d2e25b6ce3b26e6789351190b16e3a5d129efa21d2f9926a948144cf",
          "sha1": "0c08d99acc17d0e2328ea20461839664d568c726",
          "md5": "52b875ee5418cf90aca4788aebcd459b"
        }
      ]
    }
  ]
}
