{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-ui",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-ui-6.3.0-alpha.aar",
          "url": "feature-ui-6.3.0-alpha.aar",
          "size": 279179,
          "sha512": "a29efa9845dc95e0b0af1811e2841ff0c58904ae2ccfb601d4e5a46154ac5a3a930cc692b07aabb58073fc73422c8fa6bee805773027b5dbc821c0becdda15b0",
          "sha256": "9cb6459132d88cb47167002d8992eb18a50a76b1dc3723d27afdfb4b2172f3bb",
          "sha1": "50b7511002784df552e472654991fe2295775c7f",
          "md5": "8806424f4eb7a19f95689f915fa71763"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-ui-6.3.0-alpha.aar",
          "url": "feature-ui-6.3.0-alpha.aar",
          "size": 279179,
          "sha512": "a29efa9845dc95e0b0af1811e2841ff0c58904ae2ccfb601d4e5a46154ac5a3a930cc692b07aabb58073fc73422c8fa6bee805773027b5dbc821c0becdda15b0",
          "sha256": "9cb6459132d88cb47167002d8992eb18a50a76b1dc3723d27afdfb4b2172f3bb",
          "sha1": "50b7511002784df552e472654991fe2295775c7f",
          "md5": "8806424f4eb7a19f95689f915fa71763"
        }
      ]
    }
  ]
}
