{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-template-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-domain-6.3.0-alpha.jar",
          "url": "feature-template-domain-6.3.0-alpha.jar",
          "size": 2584,
          "sha512": "e7fc7331c9e4fd2f4128acfe3cb7ebea82aa600c92d7a7b0491ad8b367c467bfd20ddfe0f7f78cfeeafe5f299a6e45e4f589c34d932112d1b99ef1d0fa512406",
          "sha256": "374e8e818e8ab2efa15f39e088d2ec1d6ee565c6315a800fc33c3a3fc898fc9e",
          "sha1": "432cd57db0a502095737a44bcc440496c88a07da",
          "md5": "4c3ebf1abeec33584044ca3914ba806a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-domain-6.3.0-alpha.jar",
          "url": "feature-template-domain-6.3.0-alpha.jar",
          "size": 2584,
          "sha512": "e7fc7331c9e4fd2f4128acfe3cb7ebea82aa600c92d7a7b0491ad8b367c467bfd20ddfe0f7f78cfeeafe5f299a6e45e4f589c34d932112d1b99ef1d0fa512406",
          "sha256": "374e8e818e8ab2efa15f39e088d2ec1d6ee565c6315a800fc33c3a3fc898fc9e",
          "sha1": "432cd57db0a502095737a44bcc440496c88a07da",
          "md5": "4c3ebf1abeec33584044ca3914ba806a"
        }
      ]
    }
  ]
}
