{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.5-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.5-beta.jar",
          "size": 12877,
          "sha512": "6bd08ee1b11b3bbe8bc28ce8fbc48c55eec382faf710f263cef3ac80af5efd540b6fde77afd7bd0af9d262c120d1caaacb82bbcdb630fd02e4589fa5b29e0733",
          "sha256": "97a6206c5f12d4adfb05f9329e97985ba3d56872bcf18482f7315ea0fbfc98da",
          "sha1": "3ffb2b8ec32bfc521593235b5f94394568e749db",
          "md5": "653b438f861979454ce7a83e9e956990"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.5-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.5-beta.jar",
          "size": 12877,
          "sha512": "6bd08ee1b11b3bbe8bc28ce8fbc48c55eec382faf710f263cef3ac80af5efd540b6fde77afd7bd0af9d262c120d1caaacb82bbcdb630fd02e4589fa5b29e0733",
          "sha256": "97a6206c5f12d4adfb05f9329e97985ba3d56872bcf18482f7315ea0fbfc98da",
          "sha1": "3ffb2b8ec32bfc521593235b5f94394568e749db",
          "md5": "653b438f861979454ce7a83e9e956990"
        }
      ]
    }
  ]
}
