{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-testing",
    "version": "6.0.1.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-testing-6.0.1.1-beta.jar",
          "url": "mdlive-testing-6.0.1.1-beta.jar",
          "size": 8078,
          "sha512": "b51fa3c49b1d67a5d8f0001cad91ab1ac5b1603e5ee8cd760d33b008448cf49bf9b8582b8bab60833354bae75eb5b58f195c41260dafcec4f23aabf453236b8f",
          "sha256": "3a0f5922fece031e7b369aee9f80438d983d6a49f05a78e231a10b344869a176",
          "sha1": "5cc6505865b9999144c462bc5512c2055acdbfd8",
          "md5": "6e0052d5345645b783bd793778146308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-testing-6.0.1.1-beta.jar",
          "url": "mdlive-testing-6.0.1.1-beta.jar",
          "size": 8078,
          "sha512": "b51fa3c49b1d67a5d8f0001cad91ab1ac5b1603e5ee8cd760d33b008448cf49bf9b8582b8bab60833354bae75eb5b58f195c41260dafcec4f23aabf453236b8f",
          "sha256": "3a0f5922fece031e7b369aee9f80438d983d6a49f05a78e231a10b344869a176",
          "sha1": "5cc6505865b9999144c462bc5512c2055acdbfd8",
          "md5": "6e0052d5345645b783bd793778146308"
        }
      ]
    }
  ]
}
