{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.3-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.3-beta.jar",
          "size": 3393,
          "sha512": "23b6d3bf1074b7818a7a3c140863c506b8df004a1092b3b12573c70600721bab220348605c2ccb49295ca9569b658b668f688e6686e9f295813176230202389f",
          "sha256": "2dad561fd3ba2c6643520afa49742bff96d2d19d69314e2881021100dfa5f5c8",
          "sha1": "ed10f5fe1129408720deb24089c296543d68f1b2",
          "md5": "bd15dacc21a17f73f284f351732fd8e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.3-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.3-beta.jar",
          "size": 3393,
          "sha512": "23b6d3bf1074b7818a7a3c140863c506b8df004a1092b3b12573c70600721bab220348605c2ccb49295ca9569b658b668f688e6686e9f295813176230202389f",
          "sha256": "2dad561fd3ba2c6643520afa49742bff96d2d19d69314e2881021100dfa5f5c8",
          "sha1": "ed10f5fe1129408720deb24089c296543d68f1b2",
          "md5": "bd15dacc21a17f73f284f351732fd8e6"
        }
      ]
    }
  ]
}
