{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk-java",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-6.1.0.5-beta.jar",
          "url": "android-sdk-java-6.1.0.5-beta.jar",
          "size": 87942,
          "sha512": "d8f1a30cd849c7ad132d4e6110ec84e70a09bd0c91ed83a752fe9e1308de027e19953ef3beb5b1b96a900c34213ce59f91c2b44f87684262d01a66dd90f393b1",
          "sha256": "3322c4f655c394f318be8c8ef8b01275135e5dc82e17be581269cea1312e2794",
          "sha1": "f4d11b11faf42ebf6d6d8c5f3054a7b9ee748451",
          "md5": "25edde8f7404473803c09ae450490ca5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-6.1.0.5-beta.jar",
          "url": "android-sdk-java-6.1.0.5-beta.jar",
          "size": 87942,
          "sha512": "d8f1a30cd849c7ad132d4e6110ec84e70a09bd0c91ed83a752fe9e1308de027e19953ef3beb5b1b96a900c34213ce59f91c2b44f87684262d01a66dd90f393b1",
          "sha256": "3322c4f655c394f318be8c8ef8b01275135e5dc82e17be581269cea1312e2794",
          "sha1": "f4d11b11faf42ebf6d6d8c5f3054a7b9ee748451",
          "md5": "25edde8f7404473803c09ae450490ca5"
        }
      ]
    }
  ]
}
