{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.0-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.0-beta.jar",
          "size": 12835,
          "sha512": "676cae724e7fed77efc77df6683d748b9f4107522a1766e629f85b0ff0acffe98e67f6382c0cf810d4ca697204b00229954a0ea9880052312ccf560475a7cfc1",
          "sha256": "5dd36cc6304d7e313a5c7bb74ef2a09d9adde1485561fd4303529cc346851b5c",
          "sha1": "47c89c9511bacd6faa65525a4c1de750e714850b",
          "md5": "5a1182c4d9a828f81cf48d5a4941c9b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.0-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.0-beta.jar",
          "size": 12835,
          "sha512": "676cae724e7fed77efc77df6683d748b9f4107522a1766e629f85b0ff0acffe98e67f6382c0cf810d4ca697204b00229954a0ea9880052312ccf560475a7cfc1",
          "sha256": "5dd36cc6304d7e313a5c7bb74ef2a09d9adde1485561fd4303529cc346851b5c",
          "sha1": "47c89c9511bacd6faa65525a4c1de750e714850b",
          "md5": "5a1182c4d9a828f81cf48d5a4941c9b4"
        }
      ]
    }
  ]
}
