{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.0.1.3-beta.jar",
          "url": "mdlive-services-6.0.1.3-beta.jar",
          "size": 928090,
          "sha512": "1a90a1f541a328865d3028104b9777d808a563c42a9142ce2f9a0c043388fb61f9625399e45f1dc75d58edc5cbbe4d45d96e408b5e3b4930e0ece5cf4a8cd1ba",
          "sha256": "dc320a7b50bb13e80df5a94a4d05b0663dc9a37992c9601d13b3b9cd3102abac",
          "sha1": "62748821d52c342f73cef5728e9050cc88315593",
          "md5": "46d99217f51d99a740bce9da1a225514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.0.1.3-beta.jar",
          "url": "mdlive-services-6.0.1.3-beta.jar",
          "size": 928090,
          "sha512": "1a90a1f541a328865d3028104b9777d808a563c42a9142ce2f9a0c043388fb61f9625399e45f1dc75d58edc5cbbe4d45d96e408b5e3b4930e0ece5cf4a8cd1ba",
          "sha256": "dc320a7b50bb13e80df5a94a4d05b0663dc9a37992c9601d13b3b9cd3102abac",
          "sha1": "62748821d52c342f73cef5728e9050cc88315593",
          "md5": "46d99217f51d99a740bce9da1a225514"
        }
      ]
    }
  ]
}
