{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-core-models",
    "version": "6.0.1.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.0.1.1-beta.jar",
          "url": "mdlive-core-models-6.0.1.1-beta.jar",
          "size": 159468,
          "sha512": "e79917bc80c71b27ca5f4bfbbce8886ed76a583bdf4374e13f37408aa6768a1324da09310e06dcc88875f726c1782d3cd6dd82fbd433023f4c8a2baa7f59c737",
          "sha256": "c20dbc7a9e0c85aaba5225db6ddba41bd97976e546f0054373512fa98aeaaccb",
          "sha1": "8b7caeed8ff140533b039beb69f4f5b23ecd5e0f",
          "md5": "619c2277a7b44ce61b277780a3a7e421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.0.1.1-beta.jar",
          "url": "mdlive-core-models-6.0.1.1-beta.jar",
          "size": 159468,
          "sha512": "e79917bc80c71b27ca5f4bfbbce8886ed76a583bdf4374e13f37408aa6768a1324da09310e06dcc88875f726c1782d3cd6dd82fbd433023f4c8a2baa7f59c737",
          "sha256": "c20dbc7a9e0c85aaba5225db6ddba41bd97976e546f0054373512fa98aeaaccb",
          "sha1": "8b7caeed8ff140533b039beb69f4f5b23ecd5e0f",
          "md5": "619c2277a7b44ce61b277780a3a7e421"
        }
      ]
    }
  ]
}
