{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-data",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-data-6.3.0-alpha.aar",
          "url": "feature-dashboard-data-6.3.0-alpha.aar",
          "size": 206197,
          "sha512": "8c0a673f06cecdcea44c6902070c6d42e846fa26ba8b98d5803c38ed2f5b99f45ebc704e1eeb3804b0efa1006794544b29eb9dcbfa10000a6b4243b033f19456",
          "sha256": "c9e5c19ec3d717dce10475f80ace5bb0f2030e32852642b3171fbd0d7de07066",
          "sha1": "e0c96bd3e67cd23bbc914fc2f2df4bf9697dc56a",
          "md5": "52b4ae6968880cb56587721ec77867bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-data-6.3.0-alpha.aar",
          "url": "feature-dashboard-data-6.3.0-alpha.aar",
          "size": 206197,
          "sha512": "8c0a673f06cecdcea44c6902070c6d42e846fa26ba8b98d5803c38ed2f5b99f45ebc704e1eeb3804b0efa1006794544b29eb9dcbfa10000a6b4243b033f19456",
          "sha256": "c9e5c19ec3d717dce10475f80ace5bb0f2030e32852642b3171fbd0d7de07066",
          "sha1": "e0c96bd3e67cd23bbc914fc2f2df4bf9697dc56a",
          "md5": "52b4ae6968880cb56587721ec77867bd"
        }
      ]
    }
  ]
}
