{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-labs-ui",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-ui-6.1.0.2-beta.aar",
          "url": "feature-labs-ui-6.1.0.2-beta.aar",
          "size": 276232,
          "sha512": "8d652bda5afb9a914e3b6f0683b30d360ac0c4f4814f43a5b3a37d0a8f85bbf7d4ff47d44eb83706502ef8032507cf31882c1e60d8d980eb5518a9d45f046843",
          "sha256": "17939023cfb586733bd0aad0d69ffb67fcb08266c3f0fe93d085789045e73871",
          "sha1": "5cd89cbae2c016d85ca525390562e9a33fd4a182",
          "md5": "387ae57ce3bab8f6667a8115d1a41af0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-labs-domain",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-ui-6.1.0.2-beta.aar",
          "url": "feature-labs-ui-6.1.0.2-beta.aar",
          "size": 276232,
          "sha512": "8d652bda5afb9a914e3b6f0683b30d360ac0c4f4814f43a5b3a37d0a8f85bbf7d4ff47d44eb83706502ef8032507cf31882c1e60d8d980eb5518a9d45f046843",
          "sha256": "17939023cfb586733bd0aad0d69ffb67fcb08266c3f0fe93d085789045e73871",
          "sha1": "5cd89cbae2c016d85ca525390562e9a33fd4a182",
          "md5": "387ae57ce3bab8f6667a8115d1a41af0"
        }
      ]
    }
  ]
}
