{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.1.0.1-beta.jar",
          "url": "mdlive-common-6.1.0.1-beta.jar",
          "size": 16247,
          "sha512": "8895c2b4be4bcec8b2288d1fa4826d38dc236e069d5a6277ca664300edaa2f350283331257423d5877443bf7120e061de571d99b008179c7ae0043d09727c3b1",
          "sha256": "6a8f8d9691ad6aa7ebc6b6179bf3701a275f50d3d3d33a5c2326016e474790d1",
          "sha1": "fb06f3080a3aef6b387db8ffd361be52ffef0513",
          "md5": "87150dc283789dc1b16d888431632cc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.1.0.1-beta.jar",
          "url": "mdlive-common-6.1.0.1-beta.jar",
          "size": 16247,
          "sha512": "8895c2b4be4bcec8b2288d1fa4826d38dc236e069d5a6277ca664300edaa2f350283331257423d5877443bf7120e061de571d99b008179c7ae0043d09727c3b1",
          "sha256": "6a8f8d9691ad6aa7ebc6b6179bf3701a275f50d3d3d33a5c2326016e474790d1",
          "sha1": "fb06f3080a3aef6b387db8ffd361be52ffef0513",
          "md5": "87150dc283789dc1b16d888431632cc3"
        }
      ]
    }
  ]
}
