{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-data",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-data-6.0.1.4-beta.aar",
          "url": "feature-dashboard-data-6.0.1.4-beta.aar",
          "size": 135665,
          "sha512": "d2f2ce13a9aea487fcfe1544d434bb93534b25f6102e10bd26161912046a588ec7abec27577740b51f6efa07a083b455732a811f563a8f737b05eee9f6883da3",
          "sha256": "6bbef235a75aa785e210990d89513d00115d6388a848033b13934c3dba5a38fc",
          "sha1": "f5f55245c0e47ee18273e3ad6078afc0a1f3b3d1",
          "md5": "3dfc4138e84d4dd9a2a633023823cf14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-data-6.0.1.4-beta.aar",
          "url": "feature-dashboard-data-6.0.1.4-beta.aar",
          "size": 135665,
          "sha512": "d2f2ce13a9aea487fcfe1544d434bb93534b25f6102e10bd26161912046a588ec7abec27577740b51f6efa07a083b455732a811f563a8f737b05eee9f6883da3",
          "sha256": "6bbef235a75aa785e210990d89513d00115d6388a848033b13934c3dba5a38fc",
          "sha1": "f5f55245c0e47ee18273e3ad6078afc0a1f3b3d1",
          "md5": "3dfc4138e84d4dd9a2a633023823cf14"
        }
      ]
    }
  ]
}
