{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-core-models",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.1.0.5-beta.jar",
          "url": "mdlive-core-models-6.1.0.5-beta.jar",
          "size": 215512,
          "sha512": "daeec3807cdbe65ff1483fdbd3d9702e5458ffefbe45ae2aa6ff262d6376f5c419163b2432b44ac46311669b101274db779d926e751c5fd61001705782c5f666",
          "sha256": "de1d5678b7897e38809b8e9d8367881c0862cae5b753128c8648ccca4d7716c3",
          "sha1": "bf5ee3d62718c5bef8e95a8323799e777a2c7b89",
          "md5": "9568fd55269469030bbb270e50d08475"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.1.0.5-beta.jar",
          "url": "mdlive-core-models-6.1.0.5-beta.jar",
          "size": 215512,
          "sha512": "daeec3807cdbe65ff1483fdbd3d9702e5458ffefbe45ae2aa6ff262d6376f5c419163b2432b44ac46311669b101274db779d926e751c5fd61001705782c5f666",
          "sha256": "de1d5678b7897e38809b8e9d8367881c0862cae5b753128c8648ccca4d7716c3",
          "sha1": "bf5ee3d62718c5bef8e95a8323799e777a2c7b89",
          "md5": "9568fd55269469030bbb270e50d08475"
        }
      ]
    }
  ]
}
