{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-ui",
    "version": "6.0.1.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-ui-6.0.1.1-beta.aar",
          "url": "feature-debugmenu-ui-6.0.1.1-beta.aar",
          "size": 333559,
          "sha512": "b3b2e028c56614d1b7d30e1377ff337eef0806648f5f9b9b5d5167c5f784493e63cc72b5bc6aaf0e3254902a7ac82bb741b2f560f855454cf37b0c15b07acb01",
          "sha256": "1479b3c0d52c5f382f5683b5a451a984c676fca14e7dbf0a0550463551b408b7",
          "sha1": "98ce6d0c90b19eb60d62f754fd05337482769eed",
          "md5": "7f918f1063bc9079654ddbc4a674b3c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-data",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.45"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-ui-6.0.1.1-beta.aar",
          "url": "feature-debugmenu-ui-6.0.1.1-beta.aar",
          "size": 333559,
          "sha512": "b3b2e028c56614d1b7d30e1377ff337eef0806648f5f9b9b5d5167c5f784493e63cc72b5bc6aaf0e3254902a7ac82bb741b2f560f855454cf37b0c15b07acb01",
          "sha256": "1479b3c0d52c5f382f5683b5a451a984c676fca14e7dbf0a0550463551b408b7",
          "sha1": "98ce6d0c90b19eb60d62f754fd05337482769eed",
          "md5": "7f918f1063bc9079654ddbc4a674b3c7"
        }
      ]
    }
  ]
}
