{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-testing",
    "version": "6.0.1.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-testing-6.0.1.2-beta.jar",
          "url": "mdlive-testing-6.0.1.2-beta.jar",
          "size": 8078,
          "sha512": "3beb223702f0b1bdcf983adc8ea3353340c888f89e13348268226a24812e00891aec5d1f7c551467535a68d36f705fd1fb07a6e04e63c1101a0405ad018fab80",
          "sha256": "161f3f2f8e0ea4139cae156208b8e93a148138daec0857930b6c81c3826646bf",
          "sha1": "3d1b9f7f9b24a969fa14c288344688f79133b562",
          "md5": "b617ae1e8e9e6bf8ee9160ba10679221"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-testing-6.0.1.2-beta.jar",
          "url": "mdlive-testing-6.0.1.2-beta.jar",
          "size": 8078,
          "sha512": "3beb223702f0b1bdcf983adc8ea3353340c888f89e13348268226a24812e00891aec5d1f7c551467535a68d36f705fd1fb07a6e04e63c1101a0405ad018fab80",
          "sha256": "161f3f2f8e0ea4139cae156208b8e93a148138daec0857930b6c81c3826646bf",
          "sha1": "3d1b9f7f9b24a969fa14c288344688f79133b562",
          "md5": "b617ae1e8e9e6bf8ee9160ba10679221"
        }
      ]
    }
  ]
}
