{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-pharmacy-ui",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-pharmacy-ui-6.3.0-alpha.aar",
          "url": "feature-pharmacy-ui-6.3.0-alpha.aar",
          "size": 308482,
          "sha512": "8c4d3f89b1ef52066b3976dd693be7ff9434354c7ebbbf4d4c34038704eafaf2fcf9dcbe7714a91d2b2867e3c6ba7b5c443126732458791d38eec068fb2346ba",
          "sha256": "2ac8999361d8072350942c6ad2d3dbd267051ef095038787a4c16cab3792ae9f",
          "sha1": "ea3357da2b78a45169eab7bdd063dbcc151fe2b3",
          "md5": "d3a813125fe37984d31dba7dab6df6a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-pharmacy-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-pharmacy-ui-6.3.0-alpha.aar",
          "url": "feature-pharmacy-ui-6.3.0-alpha.aar",
          "size": 308482,
          "sha512": "8c4d3f89b1ef52066b3976dd693be7ff9434354c7ebbbf4d4c34038704eafaf2fcf9dcbe7714a91d2b2867e3c6ba7b5c443126732458791d38eec068fb2346ba",
          "sha256": "2ac8999361d8072350942c6ad2d3dbd267051ef095038787a4c16cab3792ae9f",
          "sha1": "ea3357da2b78a45169eab7bdd063dbcc151fe2b3",
          "md5": "d3a813125fe37984d31dba7dab6df6a9"
        }
      ]
    }
  ]
}
