{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-core-models",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.1.0.0-beta.jar",
          "url": "mdlive-core-models-6.1.0.0-beta.jar",
          "size": 237196,
          "sha512": "671324d4e41153b5c7019160c9dfbd94f84facabf4819a2736232c21e66b65db9c54031b7422e8949a0d906f22a36fcf8c36015da9642883fa1a5fc33a11a40b",
          "sha256": "b2cb3c36158ff21f919522f6c5000aea0e229785f90541cc854848eae64d952f",
          "sha1": "7f3316c997a866c7f1328685f7f8960cff5d136e",
          "md5": "c4e513c377ca4d1a7a568a68c2f5760e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.1.0.0-beta.jar",
          "url": "mdlive-core-models-6.1.0.0-beta.jar",
          "size": 237196,
          "sha512": "671324d4e41153b5c7019160c9dfbd94f84facabf4819a2736232c21e66b65db9c54031b7422e8949a0d906f22a36fcf8c36015da9642883fa1a5fc33a11a40b",
          "sha256": "b2cb3c36158ff21f919522f6c5000aea0e229785f90541cc854848eae64d952f",
          "sha1": "7f3316c997a866c7f1328685f7f8960cff5d136e",
          "md5": "c4e513c377ca4d1a7a568a68c2f5760e"
        }
      ]
    }
  ]
}
