{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-data",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-data-6.1.0.0-beta.aar",
          "url": "feature-dashboard-data-6.1.0.0-beta.aar",
          "size": 169656,
          "sha512": "ea36bde747e2c10bee214cd2434161a0e5b06c78486961c7273168e25caba55eb9d193c76ed68b5af9d9e6f2e77939cc95bdf80e831e415e37e202f0d4688253",
          "sha256": "dfe70c6a87a8f95f1e6eeb342defe7c8d8d50cccb932f4b331874c0a5143be58",
          "sha1": "9cb27a18c93cc480d2626ed61e9a3069a69fd74e",
          "md5": "154f430449666a98b6f2bc4faaa6aec2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-data-6.1.0.0-beta.aar",
          "url": "feature-dashboard-data-6.1.0.0-beta.aar",
          "size": 169656,
          "sha512": "ea36bde747e2c10bee214cd2434161a0e5b06c78486961c7273168e25caba55eb9d193c76ed68b5af9d9e6f2e77939cc95bdf80e831e415e37e202f0d4688253",
          "sha256": "dfe70c6a87a8f95f1e6eeb342defe7c8d8d50cccb932f4b331874c0a5143be58",
          "sha1": "9cb27a18c93cc480d2626ed61e9a3069a69fd74e",
          "md5": "154f430449666a98b6f2bc4faaa6aec2"
        }
      ]
    }
  ]
}
