{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-ui",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.3.0-alpha.aar",
          "url": "mdlive-ui-6.3.0-alpha.aar",
          "size": 3099195,
          "sha512": "c7aec9ce3b960fbb95ce9fb2ee7822ef7c0bac43bd1e134d36f3a35dcd44a233f830b04e5eccdfd79387e2c2cc20edf914f763dc92187d7fd92393ae9d9635b8",
          "sha256": "8ae16b0759ee8b745ff7d755600353bfff950f52779f41568a7928b2757e322e",
          "sha1": "72982f7cfa3c970a9aef9cb607419e89f5bd0876",
          "md5": "251d8a5eaca3f151ac8b450339021b59"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.3.0-alpha.aar",
          "url": "mdlive-ui-6.3.0-alpha.aar",
          "size": 3099195,
          "sha512": "c7aec9ce3b960fbb95ce9fb2ee7822ef7c0bac43bd1e134d36f3a35dcd44a233f830b04e5eccdfd79387e2c2cc20edf914f763dc92187d7fd92393ae9d9635b8",
          "sha256": "8ae16b0759ee8b745ff7d755600353bfff950f52779f41568a7928b2757e322e",
          "sha1": "72982f7cfa3c970a9aef9cb607419e89f5bd0876",
          "md5": "251d8a5eaca3f151ac8b450339021b59"
        }
      ]
    }
  ]
}
