{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-ui",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.3.0-alpha.aar",
          "url": "mdlive-ui-6.3.0-alpha.aar",
          "size": 3098572,
          "sha512": "39dccca3db5973eda0847303eb9745ffc20e11f65593618883353654bcc2612bed4e727c3042a8da37957d7ced2e838afa4ba4fe2533bc0924dbca7c6fa8e475",
          "sha256": "4f3f3c088eba0e279cc9cf762fee5ad7244fcbb315d51471fb93c4cd6e53a785",
          "sha1": "32c4483311c52765fb34a76e2eeb16b62702f27f",
          "md5": "286e72c620c8682885b35e5ca4bfe704"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.3.0-alpha.aar",
          "url": "mdlive-ui-6.3.0-alpha.aar",
          "size": 3098572,
          "sha512": "39dccca3db5973eda0847303eb9745ffc20e11f65593618883353654bcc2612bed4e727c3042a8da37957d7ced2e838afa4ba4fe2533bc0924dbca7c6fa8e475",
          "sha256": "4f3f3c088eba0e279cc9cf762fee5ad7244fcbb315d51471fb93c4cd6e53a785",
          "sha1": "32c4483311c52765fb34a76e2eeb16b62702f27f",
          "md5": "286e72c620c8682885b35e5ca4bfe704"
        }
      ]
    }
  ]
}
