{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.4-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.4-beta.jar",
          "size": 3393,
          "sha512": "31a3566b145cd16863a6fda8cc24af772a1ab3dc381d0b7f111c691e64890ee3a233c9acc31eb91e537fed93265dd6a1423c428c10cfc2750458130639ce214b",
          "sha256": "682a091a8c65c67e176a5c94c2c784526d6c6e3b99415800421c4abd7ba3fb05",
          "sha1": "9a4ad6285c1cc4eada1b5dcaf7f821046d25ef25",
          "md5": "a2595ae8461ab117a158a18b9f692da3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.4-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.4-beta.jar",
          "size": 3393,
          "sha512": "31a3566b145cd16863a6fda8cc24af772a1ab3dc381d0b7f111c691e64890ee3a233c9acc31eb91e537fed93265dd6a1423c428c10cfc2750458130639ce214b",
          "sha256": "682a091a8c65c67e176a5c94c2c784526d6c6e3b99415800421c4abd7ba3fb05",
          "sha1": "9a4ad6285c1cc4eada1b5dcaf7f821046d25ef25",
          "md5": "a2595ae8461ab117a158a18b9f692da3"
        }
      ]
    }
  ]
}
