{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-core-models",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.3.0-alpha.jar",
          "url": "mdlive-core-models-6.3.0-alpha.jar",
          "size": 313009,
          "sha512": "c23ee759d109b46c3a8e8f97d95997c9440b0b43b24741c24f0f9e12e6e04c9d2f075d1763652e2f22372f959897e208cba198a74b23aa944939bdce0b634317",
          "sha256": "a3b6bfefa536bb28d653a9c10a7d877391600563dfcc440ab1631094a2539a50",
          "sha1": "359ce9b276780a1a4f4e90cc41436733a8872dd9",
          "md5": "ccdded65b4cfd2d4df5a348555472cec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.3.0-alpha.jar",
          "url": "mdlive-core-models-6.3.0-alpha.jar",
          "size": 313009,
          "sha512": "c23ee759d109b46c3a8e8f97d95997c9440b0b43b24741c24f0f9e12e6e04c9d2f075d1763652e2f22372f959897e208cba198a74b23aa944939bdce0b634317",
          "sha256": "a3b6bfefa536bb28d653a9c10a7d877391600563dfcc440ab1631094a2539a50",
          "sha1": "359ce9b276780a1a4f4e90cc41436733a8872dd9",
          "md5": "ccdded65b4cfd2d4df5a348555472cec"
        }
      ]
    }
  ]
}
