{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "url": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "size": 12835,
          "sha512": "eaae6483db1bb47b11405d9170ef2174f35de2d8b077091b76b70a102cb94f63c15b69bfc0d2cd448a502a14726957393c3e40d306a81c757c1b834e74981af0",
          "sha256": "767e8b66ac9bbf91a75e9da55e585c58acc8e00d2b3782d9ae151066c3be7abc",
          "sha1": "3f0f635f33496e44cf5b57f19256546618978120",
          "md5": "2336b1adf9717f0f6c8978adf665558f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "url": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "size": 12835,
          "sha512": "eaae6483db1bb47b11405d9170ef2174f35de2d8b077091b76b70a102cb94f63c15b69bfc0d2cd448a502a14726957393c3e40d306a81c757c1b834e74981af0",
          "sha256": "767e8b66ac9bbf91a75e9da55e585c58acc8e00d2b3782d9ae151066c3be7abc",
          "sha1": "3f0f635f33496e44cf5b57f19256546618978120",
          "md5": "2336b1adf9717f0f6c8978adf665558f"
        }
      ]
    }
  ]
}
