{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "url": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "size": 12835,
          "sha512": "b681d77453496eff9eaf542187568ea70bb1c674635d888606b0b2d502c4495e6ec39ed21051d7ddd2ee80ed80264517cf273a1123fde34df661ffb8329054c0",
          "sha256": "49400cbb7f94eb258d229a2aab5b979cedc892299f2cc3c715f23a1fb8139da4",
          "sha1": "1d5f3401ec5a96e01116d9d66b44dbddb24b7670",
          "md5": "5ff14d3c317e05ffdc3cb828f4c22694"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "url": "feature-debugmenu-domain-6.3.0-alpha.jar",
          "size": 12835,
          "sha512": "b681d77453496eff9eaf542187568ea70bb1c674635d888606b0b2d502c4495e6ec39ed21051d7ddd2ee80ed80264517cf273a1123fde34df661ffb8329054c0",
          "sha256": "49400cbb7f94eb258d229a2aab5b979cedc892299f2cc3c715f23a1fb8139da4",
          "sha1": "1d5f3401ec5a96e01116d9d66b44dbddb24b7670",
          "md5": "5ff14d3c317e05ffdc3cb828f4c22694"
        }
      ]
    }
  ]
}
