{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-data",
    "version": "6.1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-data-6.1.0.1-beta.aar",
          "url": "feature-debugmenu-data-6.1.0.1-beta.aar",
          "size": 4411,
          "sha512": "5206c1436deba1d28ac917dadf2de15a3528d6e994792250a408f65140f8b6b2128cb7a9c62fece3dfe2892c0e41e600471d9f15704195270fa1fb6a2396700a",
          "sha256": "f7495a3d727b0ad2b8c119da4ffc6e54f34a52ceb81a4ce39a14c811d390a6f7",
          "sha1": "77fdd14a03d137dd20ab4ac1d7a53969e07c4589",
          "md5": "2636c70a92cf50a9c53dcbcfdda04d7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-data-6.1.0.1-beta.aar",
          "url": "feature-debugmenu-data-6.1.0.1-beta.aar",
          "size": 4411,
          "sha512": "5206c1436deba1d28ac917dadf2de15a3528d6e994792250a408f65140f8b6b2128cb7a9c62fece3dfe2892c0e41e600471d9f15704195270fa1fb6a2396700a",
          "sha256": "f7495a3d727b0ad2b8c119da4ffc6e54f34a52ceb81a4ce39a14c811d390a6f7",
          "sha1": "77fdd14a03d137dd20ab4ac1d7a53969e07c4589",
          "md5": "2636c70a92cf50a9c53dcbcfdda04d7d"
        }
      ]
    }
  ]
}
