{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.0.1.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.1-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.1-beta.jar",
          "size": 3393,
          "sha512": "be34db2c81e307412a2581fc472e00ae49ae07ce2b0c96a648cb2db51dd5557e4db7f8e0483c0b546c05c50eb7d84768695c8b098be90e70ed6f39b5aa75fb66",
          "sha256": "a9983414d0e60e03b25198499113dacee2b76a558d4b25b9bf818a0b62338d1b",
          "sha1": "fc149522fafb13d285463714fbb7f1ee5c4a4b6e",
          "md5": "f90023ee94660a5574bf27066761433c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.1-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.1-beta.jar",
          "size": 3393,
          "sha512": "be34db2c81e307412a2581fc472e00ae49ae07ce2b0c96a648cb2db51dd5557e4db7f8e0483c0b546c05c50eb7d84768695c8b098be90e70ed6f39b5aa75fb66",
          "sha256": "a9983414d0e60e03b25198499113dacee2b76a558d4b25b9bf818a0b62338d1b",
          "sha1": "fc149522fafb13d285463714fbb7f1ee5c4a4b6e",
          "md5": "f90023ee94660a5574bf27066761433c"
        }
      ]
    }
  ]
}
