{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-models",
    "version": "6.0.1.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-models-6.0.1.2-beta.jar",
          "url": "mdlive-models-6.0.1.2-beta.jar",
          "size": 2410957,
          "sha512": "b9bab1cf1d8dc551c63088dfe0fb0b498066e5d9b1d4bc6f9c7d521a83b26d64c25667d1fbee893b1ba2cbc6a84ccf879473ac979d2e51ff2866a5664729208e",
          "sha256": "1065ec4029022b9a3530999879a068d0e33b5299a7914af3fbae4e1b76fa32d5",
          "sha1": "6d775efd6c3275deadf49740e9ea05128a4d7e44",
          "md5": "cbd51e6355a2934b5b1df2fa8b56f5e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.2-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-models-6.0.1.2-beta.jar",
          "url": "mdlive-models-6.0.1.2-beta.jar",
          "size": 2410957,
          "sha512": "b9bab1cf1d8dc551c63088dfe0fb0b498066e5d9b1d4bc6f9c7d521a83b26d64c25667d1fbee893b1ba2cbc6a84ccf879473ac979d2e51ff2866a5664729208e",
          "sha256": "1065ec4029022b9a3530999879a068d0e33b5299a7914af3fbae4e1b76fa32d5",
          "sha1": "6d775efd6c3275deadf49740e9ea05128a4d7e44",
          "md5": "cbd51e6355a2934b5b1df2fa8b56f5e9"
        }
      ]
    }
  ]
}
