{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.3.0-alpha.jar",
          "url": "feature-dashboard-domain-6.3.0-alpha.jar",
          "size": 224775,
          "sha512": "e913f78d326c87ca0b775c7b244e729f5e384ff9abc32b68b8ca9cb3efaf4ab82a6790cda011aab59e28a0bc341152ec7d0d9acf113a6c4927fb89f926382af0",
          "sha256": "b0c83a38fdfd63ae4b8b60ce1c4d76378450d1938ca02c5b764d4abda9d16db2",
          "sha1": "4fb6e9aba094bd631d466494b5d3d387e4d8c5f2",
          "md5": "0adb4eab0a6a520014dcc4db3254e182"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.3.0-alpha.jar",
          "url": "feature-dashboard-domain-6.3.0-alpha.jar",
          "size": 224775,
          "sha512": "e913f78d326c87ca0b775c7b244e729f5e384ff9abc32b68b8ca9cb3efaf4ab82a6790cda011aab59e28a0bc341152ec7d0d9acf113a6c4927fb89f926382af0",
          "sha256": "b0c83a38fdfd63ae4b8b60ce1c4d76378450d1938ca02c5b764d4abda9d16db2",
          "sha1": "4fb6e9aba094bd631d466494b5d3d387e4d8c5f2",
          "md5": "0adb4eab0a6a520014dcc4db3254e182"
        }
      ]
    }
  ]
}
