{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.0.1.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.0.1.1-beta.jar",
          "url": "mdlive-services-6.0.1.1-beta.jar",
          "size": 927773,
          "sha512": "af56bf37c2bcc47091a413fb8340f176e6e0c562114496e3c44ffa60854a659286ccc05430bdc8921c6ba2488202005a3b00e67f2433c27746e1497bc4ba9e0c",
          "sha256": "d5721fa971b7a9c365aba2888762b02c7dc1384e5ceaca3b256a501ed31602c2",
          "sha1": "361a24ca74546766e46a631a1d700411af85d3c3",
          "md5": "06f7f65f92248814b07ab91ff613b284"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.0.1.1-beta.jar",
          "url": "mdlive-services-6.0.1.1-beta.jar",
          "size": 927773,
          "sha512": "af56bf37c2bcc47091a413fb8340f176e6e0c562114496e3c44ffa60854a659286ccc05430bdc8921c6ba2488202005a3b00e67f2433c27746e1497bc4ba9e0c",
          "sha256": "d5721fa971b7a9c365aba2888762b02c7dc1384e5ceaca3b256a501ed31602c2",
          "sha1": "361a24ca74546766e46a631a1d700411af85d3c3",
          "md5": "06f7f65f92248814b07ab91ff613b284"
        }
      ]
    }
  ]
}
