{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-labs-domain",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-domain-6.1.0.2-beta.jar",
          "url": "feature-labs-domain-6.1.0.2-beta.jar",
          "size": 24338,
          "sha512": "8eff6c70ba588dc15cc5f144722772747c370c10f2ba28cc00343ec4df010c03955cbe817388fd926869968ef4674fc05df5afeccb1e7a1c7e877e10bdc47a79",
          "sha256": "4603f22351c2145b7ef711e1c2e609f174daca4c6a476c7be8226abc1ae2eccf",
          "sha1": "b3724b0a6a468615bf165d27f4397d6089ded5e9",
          "md5": "09f5e1260a9929bfc1bb34f54a602d96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-domain-6.1.0.2-beta.jar",
          "url": "feature-labs-domain-6.1.0.2-beta.jar",
          "size": 24338,
          "sha512": "8eff6c70ba588dc15cc5f144722772747c370c10f2ba28cc00343ec4df010c03955cbe817388fd926869968ef4674fc05df5afeccb1e7a1c7e877e10bdc47a79",
          "sha256": "4603f22351c2145b7ef711e1c2e609f174daca4c6a476c7be8226abc1ae2eccf",
          "sha1": "b3724b0a6a468615bf165d27f4397d6089ded5e9",
          "md5": "09f5e1260a9929bfc1bb34f54a602d96"
        }
      ]
    }
  ]
}
