{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.4-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.4-beta.jar",
          "size": 12877,
          "sha512": "4d422d7c9ca5d4dd3c2f52c5d108b3c9d41ea593e8ebc852deabcc5f57d21a31decf99a756268789a4f2ad1aae0f1dcb623f3c4039ecf5c99547801ba207af51",
          "sha256": "98f269c0f346e5a842134b22fdc65d5c5264d44bf199b99e1a9d84de123c0588",
          "sha1": "39ba911650a1cc6e50485fc8c8dcfb879c4f3580",
          "md5": "fdb5d114e7b6b36019da1fbee06e3c13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.1.0.4-beta.jar",
          "url": "feature-debugmenu-domain-6.1.0.4-beta.jar",
          "size": 12877,
          "sha512": "4d422d7c9ca5d4dd3c2f52c5d108b3c9d41ea593e8ebc852deabcc5f57d21a31decf99a756268789a4f2ad1aae0f1dcb623f3c4039ecf5c99547801ba207af51",
          "sha256": "98f269c0f346e5a842134b22fdc65d5c5264d44bf199b99e1a9d84de123c0588",
          "sha1": "39ba911650a1cc6e50485fc8c8dcfb879c4f3580",
          "md5": "fdb5d114e7b6b36019da1fbee06e3c13"
        }
      ]
    }
  ]
}
