{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.1.0.2-beta.jar",
          "url": "mdlive-common-6.1.0.2-beta.jar",
          "size": 16247,
          "sha512": "776eee13ed043d0298e83b1f9dec87b12993bcec08ac5a68b1e41def7fd79163edc036f46d9f7f2c90c2e385ac60ef92794a045982e1e72953a9cd1fb72091b6",
          "sha256": "35b314d07a6e469c77e25a88bdfed6c2089585ffcbebfca343a2f00c01e39ffe",
          "sha1": "89259a6faf28f179f842580161fdd931093472c5",
          "md5": "b34b78774d24afc61fb17b6184120697"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.1.0.2-beta.jar",
          "url": "mdlive-common-6.1.0.2-beta.jar",
          "size": 16247,
          "sha512": "776eee13ed043d0298e83b1f9dec87b12993bcec08ac5a68b1e41def7fd79163edc036f46d9f7f2c90c2e385ac60ef92794a045982e1e72953a9cd1fb72091b6",
          "sha256": "35b314d07a6e469c77e25a88bdfed6c2089585ffcbebfca343a2f00c01e39ffe",
          "sha1": "89259a6faf28f179f842580161fdd931093472c5",
          "md5": "b34b78774d24afc61fb17b6184120697"
        }
      ]
    }
  ]
}
