{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-ui",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-ui-6.3.0-alpha.aar",
          "url": "feature-dashboard-ui-6.3.0-alpha.aar",
          "size": 1636641,
          "sha512": "820b36ae5aee4a4bf9fab1be849abebc802190c6de42eecf192aa7a5631e8c305d33d4c9b80625f45425ff7d92bcb7a2bda3f1ec859b4a87bf5eb84ec2afc4dc",
          "sha256": "ca151d58bcfee8a6d9fa4cfe7628c473929629cc67269dcb414cea95fc946f7a",
          "sha1": "bed708892341d7c1c0220f884d91732c0b9b64a6",
          "md5": "f2c7d1824fa334926b8ebff66b2b5054"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-ui-6.3.0-alpha.aar",
          "url": "feature-dashboard-ui-6.3.0-alpha.aar",
          "size": 1636641,
          "sha512": "820b36ae5aee4a4bf9fab1be849abebc802190c6de42eecf192aa7a5631e8c305d33d4c9b80625f45425ff7d92bcb7a2bda3f1ec859b4a87bf5eb84ec2afc4dc",
          "sha256": "ca151d58bcfee8a6d9fa4cfe7628c473929629cc67269dcb414cea95fc946f7a",
          "sha1": "bed708892341d7c1c0220f884d91732c0b9b64a6",
          "md5": "f2c7d1824fa334926b8ebff66b2b5054"
        }
      ]
    }
  ]
}
