{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-ui",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-ui-6.1.0.5-beta.aar",
          "url": "feature-dashboard-ui-6.1.0.5-beta.aar",
          "size": 1552182,
          "sha512": "db6e8953c896b8ff628612b54386b2446f8a3b47a53220c2d54c232c840c32c66aab86cf809621f0295b6d4378bf378efc4e89505b72e8c3e02f6b0227e8ddbb",
          "sha256": "339e57913f7162c3180f65b67fcfabb4b325074c9c22ec89a9ed7f63bff3e737",
          "sha1": "23a0c9f790ff18fe19f741f2b0710e50d2faef86",
          "md5": "49d50f166176cf9e5b998a1c4af4e9b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-ui-6.1.0.5-beta.aar",
          "url": "feature-dashboard-ui-6.1.0.5-beta.aar",
          "size": 1552182,
          "sha512": "db6e8953c896b8ff628612b54386b2446f8a3b47a53220c2d54c232c840c32c66aab86cf809621f0295b6d4378bf378efc4e89505b72e8c3e02f6b0227e8ddbb",
          "sha256": "339e57913f7162c3180f65b67fcfabb4b325074c9c22ec89a9ed7f63bff3e737",
          "sha1": "23a0c9f790ff18fe19f741f2b0710e50d2faef86",
          "md5": "49d50f166176cf9e5b998a1c4af4e9b0"
        }
      ]
    }
  ]
}
