{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.1.0.4-beta.jar",
          "url": "mdlive-services-6.1.0.4-beta.jar",
          "size": 936590,
          "sha512": "e52ce0a8fbeb0c95677f709a035605d0efff5c221c8ecb4a3b06c37e786c57089c02a89b5d36eaf2214ed6b72a72b1d9b10f93ccbb50e53cba7f1a19c4aaad19",
          "sha256": "adcd7eeb600df6a2cb92d16f77603e7ce5eece3e1c98d981c18e8c72e913b375",
          "sha1": "0a6656bd0b9d45226695c93c316fba95ea9d3d99",
          "md5": "a0d73203ca34fc1fc77933f7125ed382"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.1.0.4-beta.jar",
          "url": "mdlive-services-6.1.0.4-beta.jar",
          "size": 936590,
          "sha512": "e52ce0a8fbeb0c95677f709a035605d0efff5c221c8ecb4a3b06c37e786c57089c02a89b5d36eaf2214ed6b72a72b1d9b10f93ccbb50e53cba7f1a19c4aaad19",
          "sha256": "adcd7eeb600df6a2cb92d16f77603e7ce5eece3e1c98d981c18e8c72e913b375",
          "sha1": "0a6656bd0b9d45226695c93c316fba95ea9d3d99",
          "md5": "a0d73203ca34fc1fc77933f7125ed382"
        }
      ]
    }
  ]
}
