{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk-java-android-sdk-java",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "url": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "size": 96333,
          "sha512": "b9e3fc951f34866c396431f660c7777fd3ea9993aafc0ece949034e1597ea4b122225da9f477ea8e9f9336eff7a19458671baafa50c7de8c55a5665baeab9ded",
          "sha256": "893508f0bced64993d92e53b2186b160766ac3446259e040dd91b4572ae550ff",
          "sha1": "d4d2de08a560e299809e10d48254ed1fb327632b",
          "md5": "913010a6fe838509838f3bffb7a2609e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "url": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "size": 96333,
          "sha512": "b9e3fc951f34866c396431f660c7777fd3ea9993aafc0ece949034e1597ea4b122225da9f477ea8e9f9336eff7a19458671baafa50c7de8c55a5665baeab9ded",
          "sha256": "893508f0bced64993d92e53b2186b160766ac3446259e040dd91b4572ae550ff",
          "sha1": "d4d2de08a560e299809e10d48254ed1fb327632b",
          "md5": "913010a6fe838509838f3bffb7a2609e"
        }
      ]
    }
  ]
}
