{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk-java-android-sdk-java",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "url": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "size": 96333,
          "sha512": "b362bc809a84fc736b051e7e14c323c1d5badf2f3a51413ca177fa82415137b644eff63a7cdc6972caaba3819a505dfc5f64a9a294708f0fad21b0b258f8914e",
          "sha256": "af5f30fa3b8b03f63848b3a6201efd6a25117518b9f37203bf424f0f7b53be51",
          "sha1": "a88e3cdae1783348161c3421173b482dcb65f900",
          "md5": "05f3299bde6fdd5c329ea7f9f859ebfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "url": "android-sdk-java-android-sdk-java-6.3.0-alpha.jar",
          "size": 96333,
          "sha512": "b362bc809a84fc736b051e7e14c323c1d5badf2f3a51413ca177fa82415137b644eff63a7cdc6972caaba3819a505dfc5f64a9a294708f0fad21b0b258f8914e",
          "sha256": "af5f30fa3b8b03f63848b3a6201efd6a25117518b9f37203bf424f0f7b53be51",
          "sha1": "a88e3cdae1783348161c3421173b482dcb65f900",
          "md5": "05f3299bde6fdd5c329ea7f9f859ebfa"
        }
      ]
    }
  ]
}
