{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-pharmacy-data",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-pharmacy-data-6.3.0-alpha.aar",
          "url": "feature-pharmacy-data-6.3.0-alpha.aar",
          "size": 22335,
          "sha512": "7bd2e8e1bcd32677d46c759c9c9c659a374fa5c3996602b4c3a9cbe1f5f83d7368680ed979c9a9a11b83a63a2259a9b3a28a51dfd146e7e88856a7cc611ab267",
          "sha256": "5ddc8b020d5cef6c78c1527e120a872ab5e5de5a241547b16933a92acb250091",
          "sha1": "0d597483d74e8c3d97870f2bc57f9188f1192792",
          "md5": "9451bc1d8d21f209e8b5e0c9523fb9d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-pharmacy-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-pharmacy-data-6.3.0-alpha.aar",
          "url": "feature-pharmacy-data-6.3.0-alpha.aar",
          "size": 22335,
          "sha512": "7bd2e8e1bcd32677d46c759c9c9c659a374fa5c3996602b4c3a9cbe1f5f83d7368680ed979c9a9a11b83a63a2259a9b3a28a51dfd146e7e88856a7cc611ab267",
          "sha256": "5ddc8b020d5cef6c78c1527e120a872ab5e5de5a241547b16933a92acb250091",
          "sha1": "0d597483d74e8c3d97870f2bc57f9188f1192792",
          "md5": "9451bc1d8d21f209e8b5e0c9523fb9d6"
        }
      ]
    }
  ]
}
