{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-models",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-models-6.1.0.2-beta.jar",
          "url": "mdlive-models-6.1.0.2-beta.jar",
          "size": 2430467,
          "sha512": "b6dbb0b41cb6d515f2409b6b6ccc212147e8734d33edc3fee55510051f5255bb582c1e4cce4973379f1582c94af5cb93e9ffeb97ba7823523ca9297f3b906ba3",
          "sha256": "5601b2adb15e2a71acbb25ab62034afaa50af9a893b908cf8781f2fcba5b3fa5",
          "sha1": "5b957cedae138f368a1f0fc1093f3cde3a61f888",
          "md5": "13723c60798f9ba81ed0ed79722f5309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-models-6.1.0.2-beta.jar",
          "url": "mdlive-models-6.1.0.2-beta.jar",
          "size": 2430467,
          "sha512": "b6dbb0b41cb6d515f2409b6b6ccc212147e8734d33edc3fee55510051f5255bb582c1e4cce4973379f1582c94af5cb93e9ffeb97ba7823523ca9297f3b906ba3",
          "sha256": "5601b2adb15e2a71acbb25ab62034afaa50af9a893b908cf8781f2fcba5b3fa5",
          "sha1": "5b957cedae138f368a1f0fc1093f3cde3a61f888",
          "md5": "13723c60798f9ba81ed0ed79722f5309"
        }
      ]
    }
  ]
}
