{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.0.1.3-beta.jar",
          "url": "mdlive-common-6.0.1.3-beta.jar",
          "size": 15516,
          "sha512": "3e1eb5c7378656af6afa13d8bbb65369634389f686a91523f1e3c6020ff61ff4a179a35c0d5dc285b07a9e147ea34724152492e01a96409127c91ca8139161ec",
          "sha256": "83a63d7e0165decdde267184e60355cba640615407e113b020f7ecff40a0bd45",
          "sha1": "68171f82e87bcc28798a6738ac90e7c22a2b9a5c",
          "md5": "a49341b1d30d578952fad93ae845f5de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.0.1.3-beta.jar",
          "url": "mdlive-common-6.0.1.3-beta.jar",
          "size": 15516,
          "sha512": "3e1eb5c7378656af6afa13d8bbb65369634389f686a91523f1e3c6020ff61ff4a179a35c0d5dc285b07a9e147ea34724152492e01a96409127c91ca8139161ec",
          "sha256": "83a63d7e0165decdde267184e60355cba640615407e113b020f7ecff40a0bd45",
          "sha1": "68171f82e87bcc28798a6738ac90e7c22a2b9a5c",
          "md5": "a49341b1d30d578952fad93ae845f5de"
        }
      ]
    }
  ]
}
