{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk-common",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-common-6.1.0.4-beta.aar",
          "url": "android-sdk-common-6.1.0.4-beta.aar",
          "size": 18063,
          "sha512": "a645b3cadfa7ef7a774b71c7ddd9ade64536b1559f24746d7d6e571fdb6a64058c6bc15ab5a9a037e1e09308c3e0410b6d3fc1ba708064a2a6a809311dd6850c",
          "sha256": "03ce582d95b7b21b565195d569b86bece0d5178733c57ac9bfdbcb720caa800e",
          "sha1": "2c1bc275a7979f66e5d6126262677c68fe999eda",
          "md5": "d24070a942ac5a236644697a4240b77c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-common-6.1.0.4-beta.aar",
          "url": "android-sdk-common-6.1.0.4-beta.aar",
          "size": 18063,
          "sha512": "a645b3cadfa7ef7a774b71c7ddd9ade64536b1559f24746d7d6e571fdb6a64058c6bc15ab5a9a037e1e09308c3e0410b6d3fc1ba708064a2a6a809311dd6850c",
          "sha256": "03ce582d95b7b21b565195d569b86bece0d5178733c57ac9bfdbcb720caa800e",
          "sha1": "2c1bc275a7979f66e5d6126262677c68fe999eda",
          "md5": "d24070a942ac5a236644697a4240b77c"
        }
      ]
    }
  ]
}
