{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.3.0-alpha.jar",
          "url": "mdlive-common-6.3.0-alpha.jar",
          "size": 16247,
          "sha512": "ea955de63573d7df88fb72e06dd043146666e2336535010836a0efb6e6f5085af1900cef490959b64cd725f6efcbd0e3833761ced267f04e53128109d61f2b46",
          "sha256": "f24450cb5759a6ff8a5cbc33271d8b322b6f228cdfce76ec2990ba29726fb622",
          "sha1": "5e72b57eb653887b02e7ca0a8f6d56b4efe85773",
          "md5": "02b328678d488487007cfcccbb64c3a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.3.0-alpha.jar",
          "url": "mdlive-common-6.3.0-alpha.jar",
          "size": 16247,
          "sha512": "ea955de63573d7df88fb72e06dd043146666e2336535010836a0efb6e6f5085af1900cef490959b64cd725f6efcbd0e3833761ced267f04e53128109d61f2b46",
          "sha256": "f24450cb5759a6ff8a5cbc33271d8b322b6f228cdfce76ec2990ba29726fb622",
          "sha1": "5e72b57eb653887b02e7ca0a8f6d56b4efe85773",
          "md5": "02b328678d488487007cfcccbb64c3a6"
        }
      ]
    }
  ]
}
