{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-domain",
    "version": "6.0.1.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.2-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.2-beta.jar",
          "size": 3393,
          "sha512": "44c8f07502b57487bab93dbb8bec3eabd0c0ecf766a464523af05fdbcab0feffe9dd7a1a75ae8f4092c441d86c335574a0b837be5cea7a47b72eb0e698c42b7c",
          "sha256": "f98ee3842bd765436b83afcfda68b94f35e7aa936403dd8a51406429147d0cbb",
          "sha1": "33da7ddc24ee513e0c13a1d487d335e10649e669",
          "md5": "5e52505c5e838d427c3a8d164a8d8dce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-domain-6.0.1.2-beta.jar",
          "url": "feature-debugmenu-domain-6.0.1.2-beta.jar",
          "size": 3393,
          "sha512": "44c8f07502b57487bab93dbb8bec3eabd0c0ecf766a464523af05fdbcab0feffe9dd7a1a75ae8f4092c441d86c335574a0b837be5cea7a47b72eb0e698c42b7c",
          "sha256": "f98ee3842bd765436b83afcfda68b94f35e7aa936403dd8a51406429147d0cbb",
          "sha1": "33da7ddc24ee513e0c13a1d487d335e10649e669",
          "md5": "5e52505c5e838d427c3a8d164a8d8dce"
        }
      ]
    }
  ]
}
