{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-models",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-models-6.1.0.0-beta.jar",
          "url": "mdlive-models-6.1.0.0-beta.jar",
          "size": 2430467,
          "sha512": "4f96152d2e788f98aa4dfd5938e59135c3193cea747fc72825c74908387a637d21a1003518f79a1eb0ce3c36638f676894d98ad58aad2c3fa922b94e6d8d710d",
          "sha256": "2c27c0272094baa977ad5a778a1a716474f0d96181523a8431ec7671746ccf1a",
          "sha1": "807fdce909c9bc9367a1f8d8bfa648a74ef27c5b",
          "md5": "caf058ef25dce105408ce1031f605fe2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-models-6.1.0.0-beta.jar",
          "url": "mdlive-models-6.1.0.0-beta.jar",
          "size": 2430467,
          "sha512": "4f96152d2e788f98aa4dfd5938e59135c3193cea747fc72825c74908387a637d21a1003518f79a1eb0ce3c36638f676894d98ad58aad2c3fa922b94e6d8d710d",
          "sha256": "2c27c0272094baa977ad5a778a1a716474f0d96181523a8431ec7671746ccf1a",
          "sha1": "807fdce909c9bc9367a1f8d8bfa648a74ef27c5b",
          "md5": "caf058ef25dce105408ce1031f605fe2"
        }
      ]
    }
  ]
}
