{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-models",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-models-6.1.0.5-beta.jar",
          "url": "mdlive-models-6.1.0.5-beta.jar",
          "size": 2414249,
          "sha512": "2cf1ce9bbba790066efd6a711cedadb831c031152b6194ed8ee6525f098e13ae5de3a47a827dab2d2082bdc844e04daf99cd49ab55c5b8f70862b9f90ce9ea3c",
          "sha256": "2d968f17e799fa618f997a2ad1a80d86d0d3f1240ad4964027a5d5503c1c6ebe",
          "sha1": "0a9e3aa28dd50e55a5c978d3489c0c3347cb4b20",
          "md5": "8fcab46a1f3e80d0b4691187246e7678"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-models-6.1.0.5-beta.jar",
          "url": "mdlive-models-6.1.0.5-beta.jar",
          "size": 2414249,
          "sha512": "2cf1ce9bbba790066efd6a711cedadb831c031152b6194ed8ee6525f098e13ae5de3a47a827dab2d2082bdc844e04daf99cd49ab55c5b8f70862b9f90ce9ea3c",
          "sha256": "2d968f17e799fa618f997a2ad1a80d86d0d3f1240ad4964027a5d5503c1c6ebe",
          "sha1": "0a9e3aa28dd50e55a5c978d3489c0c3347cb4b20",
          "md5": "8fcab46a1f3e80d0b4691187246e7678"
        }
      ]
    }
  ]
}
