{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-testing",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-testing-6.1.0.5-beta.jar",
          "url": "mdlive-testing-6.1.0.5-beta.jar",
          "size": 8123,
          "sha512": "a1c1952eabd2d3f5683648f81fc8ba806f5f2f96f9649961d92de0ffaf3498d6e40324eaf0bbc4eb92e50208a56f62233243a37a302f33a6d3e435003382a0a6",
          "sha256": "008911fa70f8759317e3e27f8e78770dc9c53312e24f9eb7055b1089df5f6928",
          "sha1": "ba35ba9cc85aadeb05dd751ce7faaff2a801a936",
          "md5": "ef7acff5a7a0e9e9e56f6bbfeb8c8806"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-testing-6.1.0.5-beta.jar",
          "url": "mdlive-testing-6.1.0.5-beta.jar",
          "size": 8123,
          "sha512": "a1c1952eabd2d3f5683648f81fc8ba806f5f2f96f9649961d92de0ffaf3498d6e40324eaf0bbc4eb92e50208a56f62233243a37a302f33a6d3e435003382a0a6",
          "sha256": "008911fa70f8759317e3e27f8e78770dc9c53312e24f9eb7055b1089df5f6928",
          "sha1": "ba35ba9cc85aadeb05dd751ce7faaff2a801a936",
          "md5": "ef7acff5a7a0e9e9e56f6bbfeb8c8806"
        }
      ]
    }
  ]
}
