{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-common-android-sdk-common",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-6.0.1.4-beta.aar",
          "url": "android-sdk-6.0.1.4-beta.aar",
          "size": 23071,
          "sha512": "cedc486b31516dca58e24e750dcf842dbb32eb0af69989f6bc3f37f72bcc33e38d15d120ba69c65921f09906ae80fabac7d46cc52a55fb246aaf9edb01b7eb63",
          "sha256": "ce7ccc635533bdc92579b08d20447980ff30a217a056d97f0ef88c3072c07da5",
          "sha1": "17438606232eaed4fe092f117fc420407ab18603",
          "md5": "548bb0a58fd56e57d83cd33f5bdabdd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-common-android-sdk-common",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-core",
          "version": {
            "requires": "6.0.1.4-beta"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-6.0.1.4-beta.aar",
          "url": "android-sdk-6.0.1.4-beta.aar",
          "size": 23071,
          "sha512": "cedc486b31516dca58e24e750dcf842dbb32eb0af69989f6bc3f37f72bcc33e38d15d120ba69c65921f09906ae80fabac7d46cc52a55fb246aaf9edb01b7eb63",
          "sha256": "ce7ccc635533bdc92579b08d20447980ff30a217a056d97f0ef88c3072c07da5",
          "sha1": "17438606232eaed4fe092f117fc420407ab18603",
          "md5": "548bb0a58fd56e57d83cd33f5bdabdd8"
        }
      ]
    }
  ]
}
