{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.5-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.5-beta.jar",
          "size": 208080,
          "sha512": "37f45d0d7c386054331b7a94a070d69db14bccfae4756d499e2fca6f9568b3a8fefae5b8f2573b924784dae5c326c08a0d4dfe6a7020d9e1b5c03371caa5174b",
          "sha256": "5fe987dffe2e9f9767d561e5487da205d32f4b7f41ca6b3d1fff67ac63837575",
          "sha1": "9d577e79db67a67d65f199265ef41fac48c1a469",
          "md5": "9a0b6cf5c9427612de92ce1b727b71eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.5-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.5-beta.jar",
          "size": 208080,
          "sha512": "37f45d0d7c386054331b7a94a070d69db14bccfae4756d499e2fca6f9568b3a8fefae5b8f2573b924784dae5c326c08a0d4dfe6a7020d9e1b5c03371caa5174b",
          "sha256": "5fe987dffe2e9f9767d561e5487da205d32f4b7f41ca6b3d1fff67ac63837575",
          "sha1": "9d577e79db67a67d65f199265ef41fac48c1a469",
          "md5": "9a0b6cf5c9427612de92ce1b727b71eb"
        }
      ]
    }
  ]
}
