{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-account-recovery-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "url": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "size": 61599,
          "sha512": "5734d66449d1ffc5769ac0b623c5a6625aaad9e197498fe8ac85b99873e44302047aeae1c419790532859df3b425289250f9b78a233202aaf4746e40ed9f861c",
          "sha256": "206722d4b0877a306b994c550625d6d5957fea86b3554a4fb05144bad6d411a6",
          "sha1": "4ba68d2f35ddf3f53d467cc503eaa7401ec2fb6a",
          "md5": "4bf10f0f0310bf67de1f282918617ffe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "url": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "size": 61599,
          "sha512": "5734d66449d1ffc5769ac0b623c5a6625aaad9e197498fe8ac85b99873e44302047aeae1c419790532859df3b425289250f9b78a233202aaf4746e40ed9f861c",
          "sha256": "206722d4b0877a306b994c550625d6d5957fea86b3554a4fb05144bad6d411a6",
          "sha1": "4ba68d2f35ddf3f53d467cc503eaa7401ec2fb6a",
          "md5": "4bf10f0f0310bf67de1f282918617ffe"
        }
      ]
    }
  ]
}
