{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-account-recovery-domain",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "url": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "size": 61599,
          "sha512": "838a7aa243fcc5c423f03daf580bd46cf3faa3c4d8857db61a9580e20de5e07136a4399fd05c0bb271c25b4d07048d40cfd1fb6a648495e991a85b058f747fcb",
          "sha256": "53a13c8c126451d892bfebdf6df0b10508147d573956d1330b9a53572baf743d",
          "sha1": "93da030f025fe614b5c604382f5efb26bde4de39",
          "md5": "31c78daed2ddb0614b3505a6662897a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "url": "feature-account-recovery-domain-6.3.0-alpha.jar",
          "size": 61599,
          "sha512": "838a7aa243fcc5c423f03daf580bd46cf3faa3c4d8857db61a9580e20de5e07136a4399fd05c0bb271c25b4d07048d40cfd1fb6a648495e991a85b058f747fcb",
          "sha256": "53a13c8c126451d892bfebdf6df0b10508147d573956d1330b9a53572baf743d",
          "sha1": "93da030f025fe614b5c604382f5efb26bde4de39",
          "md5": "31c78daed2ddb0614b3505a6662897a3"
        }
      ]
    }
  ]
}
