{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-core",
    "version": "6.1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-6.1.0.1-beta.aar",
          "url": "mdlive-core-6.1.0.1-beta.aar",
          "size": 104618,
          "sha512": "0d472a9285e4d3c0a4eb1566d99ee7573cae410fef9caef29ee8644873632c4846222ee7309e8eb609f388ac2bff1655a547cb51c0fb4dc989b2be3a273e2ec1",
          "sha256": "8e6268555643f1f59abc7cfdf05647595f16a95d52727070a7a26b87f303c420",
          "sha1": "0440f3c99b1c554d9a4d62b5f5967bfed06d09d8",
          "md5": "970868c5a2c5a09d2d919493d073bff8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-ui",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-data",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-ui",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-data",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "MDLive.feature-labs",
          "module": "ui",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "MDLive.feature-labs",
          "module": "data",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "MDLive.feature-labs",
          "module": "domain",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-6.1.0.1-beta.aar",
          "url": "mdlive-core-6.1.0.1-beta.aar",
          "size": 104618,
          "sha512": "0d472a9285e4d3c0a4eb1566d99ee7573cae410fef9caef29ee8644873632c4846222ee7309e8eb609f388ac2bff1655a547cb51c0fb4dc989b2be3a273e2ec1",
          "sha256": "8e6268555643f1f59abc7cfdf05647595f16a95d52727070a7a26b87f303c420",
          "sha1": "0440f3c99b1c554d9a4d62b5f5967bfed06d09d8",
          "md5": "970868c5a2c5a09d2d919493d073bff8"
        }
      ]
    }
  ]
}
