{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-testing",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-testing-6.0.1.3-beta.jar",
          "url": "mdlive-testing-6.0.1.3-beta.jar",
          "size": 8078,
          "sha512": "1fed52364bacc13de9deebbbd085740ae540ce077bf0ce7ce650303cb62cd997edc6e33e8feb2ecb96b89c219624b595c99133915f535bbdeeedc5ad458d9476",
          "sha256": "479aa7aeebcd606592ae66ce576b784ab7efade23c3f72893860a9df37a9274b",
          "sha1": "36c491714461689d7c90054ad90e0c73a910a392",
          "md5": "a556271e4079a80a72037e704a924efb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-testing-6.0.1.3-beta.jar",
          "url": "mdlive-testing-6.0.1.3-beta.jar",
          "size": 8078,
          "sha512": "1fed52364bacc13de9deebbbd085740ae540ce077bf0ce7ce650303cb62cd997edc6e33e8feb2ecb96b89c219624b595c99133915f535bbdeeedc5ad458d9476",
          "sha256": "479aa7aeebcd606592ae66ce576b784ab7efade23c3f72893860a9df37a9274b",
          "sha1": "36c491714461689d7c90054ad90e0c73a910a392",
          "md5": "a556271e4079a80a72037e704a924efb"
        }
      ]
    }
  ]
}
