{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.1.0.2-beta.jar",
          "url": "mdlive-services-6.1.0.2-beta.jar",
          "size": 935803,
          "sha512": "5946c203c631854d16742be48bf0a88f840bee4e178bb05f92d5c9a9c275dd39a818b78da0dd91c742acc8711788c74b195e542e1c7b0aab8dec0e27bf66ac40",
          "sha256": "46e56a2624559fd19ed15e7e0643439de2ac43f20e167a218f0e0110c3ae3c5f",
          "sha1": "35eba1ae64e8ba15eb2fdb01ff9ad87cf9e4f799",
          "md5": "5c16970ceba733d8c0fb09cd0f1f0189"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.1.0.2-beta.jar",
          "url": "mdlive-services-6.1.0.2-beta.jar",
          "size": 935803,
          "sha512": "5946c203c631854d16742be48bf0a88f840bee4e178bb05f92d5c9a9c275dd39a818b78da0dd91c742acc8711788c74b195e542e1c7b0aab8dec0e27bf66ac40",
          "sha256": "46e56a2624559fd19ed15e7e0643439de2ac43f20e167a218f0e0110c3ae3c5f",
          "sha1": "35eba1ae64e8ba15eb2fdb01ff9ad87cf9e4f799",
          "md5": "5c16970ceba733d8c0fb09cd0f1f0189"
        }
      ]
    }
  ]
}
