{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.1.0.5-beta.jar",
          "url": "mdlive-common-6.1.0.5-beta.jar",
          "size": 15538,
          "sha512": "91a62b686123e9001f88a541c5011c4b64d9e1348d32a07b33ea8cddfc4dddb11fd32b9bfac8d96987c54d59e37244d8e5aff650e943f2f59cc40f927d4316d6",
          "sha256": "1b6a51adc4bbbb66384f64e62d5a0eac1300ae02781402dcdd64be2ca600ba43",
          "sha1": "8c4a6fb77c45f15a79308bda0deeaf2d2dfdc68f",
          "md5": "5a080f001778424373f335180361d116"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.1.0.5-beta.jar",
          "url": "mdlive-common-6.1.0.5-beta.jar",
          "size": 15538,
          "sha512": "91a62b686123e9001f88a541c5011c4b64d9e1348d32a07b33ea8cddfc4dddb11fd32b9bfac8d96987c54d59e37244d8e5aff650e943f2f59cc40f927d4316d6",
          "sha256": "1b6a51adc4bbbb66384f64e62d5a0eac1300ae02781402dcdd64be2ca600ba43",
          "sha1": "8c4a6fb77c45f15a79308bda0deeaf2d2dfdc68f",
          "md5": "5a080f001778424373f335180361d116"
        }
      ]
    }
  ]
}
