{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.0.1.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.0.1.2-beta.jar",
          "url": "mdlive-services-6.0.1.2-beta.jar",
          "size": 928090,
          "sha512": "f11bc34b9cbc159948e8c1ee6957337f5514dec70a84f130fc3c176c1aaf5736660e22b81ca4c9244503844537811f37b3177c68606d6688a8fd5a18da547fd9",
          "sha256": "25ed5369827d2df21b7f4d8332e6d88d764dae66b3e7983e9538f7b9e771c428",
          "sha1": "eac9777652bed67bcab3267e44743738cee41b06",
          "md5": "84345c7d7bdaa7d628af3612e53d3736"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.0.1.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.0.1.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.2-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.0.1.2-beta.jar",
          "url": "mdlive-services-6.0.1.2-beta.jar",
          "size": 928090,
          "sha512": "f11bc34b9cbc159948e8c1ee6957337f5514dec70a84f130fc3c176c1aaf5736660e22b81ca4c9244503844537811f37b3177c68606d6688a8fd5a18da547fd9",
          "sha256": "25ed5369827d2df21b7f4d8332e6d88d764dae66b3e7983e9538f7b9e771c428",
          "sha1": "eac9777652bed67bcab3267e44743738cee41b06",
          "md5": "84345c7d7bdaa7d628af3612e53d3736"
        }
      ]
    }
  ]
}
