{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-testing",
    "version": "6.0.1.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-testing-6.0.1.4-beta.jar",
          "url": "mdlive-testing-6.0.1.4-beta.jar",
          "size": 8078,
          "sha512": "e81adad791f6bb7eba6943e7c6db7bd9d80453ecbdc7c076b9964f677633304424252b64102cba2a8a8cddda642d51fd689952545ddc693a042a322aaf1f13f1",
          "sha256": "179ae6b4b2e7b0b6f96aea6b75dd8e6ed1c90423cf04536d7e4dea72c2f31c67",
          "sha1": "45bc740ba914f7a7f03b7442c87045d3979fa5d3",
          "md5": "f3a17cfdb7b8b800cdfe17553a14b279"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-testing-6.0.1.4-beta.jar",
          "url": "mdlive-testing-6.0.1.4-beta.jar",
          "size": 8078,
          "sha512": "e81adad791f6bb7eba6943e7c6db7bd9d80453ecbdc7c076b9964f677633304424252b64102cba2a8a8cddda642d51fd689952545ddc693a042a322aaf1f13f1",
          "sha256": "179ae6b4b2e7b0b6f96aea6b75dd8e6ed1c90423cf04536d7e4dea72c2f31c67",
          "sha1": "45bc740ba914f7a7f03b7442c87045d3979fa5d3",
          "md5": "f3a17cfdb7b8b800cdfe17553a14b279"
        }
      ]
    }
  ]
}
