{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-common-android-sdk-common",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-6.0.1.3-beta.aar",
          "url": "android-sdk-6.0.1.3-beta.aar",
          "size": 23071,
          "sha512": "9bf3ad2569fdb497617fd76f64a34a315585036c491e965691cea9e41e2e0284fab4d022440bd40505b722287caf1cde66635b30c18d0a002ae9d8f9c2ea9e34",
          "sha256": "d6cce12fe20f84fa9561f48bcfa62f15674aa3dfb4c727f49c5b27e387dd71a9",
          "sha1": "7fdb6bf98d0dfb029de62a10063828378aca7789",
          "md5": "e480198d3fbc52d10e77e31e59dcae03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-common-android-sdk-common",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java-android-sdk-java",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-core",
          "version": {
            "requires": "6.0.1.3-beta"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-6.0.1.3-beta.aar",
          "url": "android-sdk-6.0.1.3-beta.aar",
          "size": 23071,
          "sha512": "9bf3ad2569fdb497617fd76f64a34a315585036c491e965691cea9e41e2e0284fab4d022440bd40505b722287caf1cde66635b30c18d0a002ae9d8f9c2ea9e34",
          "sha256": "d6cce12fe20f84fa9561f48bcfa62f15674aa3dfb4c727f49c5b27e387dd71a9",
          "sha1": "7fdb6bf98d0dfb029de62a10063828378aca7789",
          "md5": "e480198d3fbc52d10e77e31e59dcae03"
        }
      ]
    }
  ]
}
