{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-services",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-services-6.1.0.0-beta.jar",
          "url": "mdlive-services-6.1.0.0-beta.jar",
          "size": 935803,
          "sha512": "a13b3ad7452a0e47bc53482c1de17a01c042ec7bb0ce42f5d29750fdcc9372aa77f5865dbb3bc1c20b74b28a412acf9964e2b9b1e87c0e58b790ca07fc47430d",
          "sha256": "40b080cd68cbd58de8ca89b998e9dcf8415827789727a49e6531d6df250426fb",
          "sha1": "e5172b0b00307bfd00d3e1b501b4b6159b19d973",
          "md5": "afbf65e4eeb69ba43b323dc78ce1d36f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-services-6.1.0.0-beta.jar",
          "url": "mdlive-services-6.1.0.0-beta.jar",
          "size": 935803,
          "sha512": "a13b3ad7452a0e47bc53482c1de17a01c042ec7bb0ce42f5d29750fdcc9372aa77f5865dbb3bc1c20b74b28a412acf9964e2b9b1e87c0e58b790ca07fc47430d",
          "sha256": "40b080cd68cbd58de8ca89b998e9dcf8415827789727a49e6531d6df250426fb",
          "sha1": "e5172b0b00307bfd00d3e1b501b4b6159b19d973",
          "md5": "afbf65e4eeb69ba43b323dc78ce1d36f"
        }
      ]
    }
  ]
}
