{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.1-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.1-beta.jar",
          "size": 208128,
          "sha512": "c800a2a43197a09fab9c822d29f9d521dba853f360992ed6ae51f4433bf170b62a58e6091923c65f2366831815363f0a44da5fbdada4109ce7fa9d562a17974d",
          "sha256": "c4c569d1e26e08008873e3a6cf2d967d72e7b782e4a7be3cb505e410f3dee395",
          "sha1": "97b140864026a09ad2a5197e69973f5c59a4b021",
          "md5": "8bee963ec21886d52ed495a6f09da0f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.1-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.1-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.1-beta.jar",
          "size": 208128,
          "sha512": "c800a2a43197a09fab9c822d29f9d521dba853f360992ed6ae51f4433bf170b62a58e6091923c65f2366831815363f0a44da5fbdada4109ce7fa9d562a17974d",
          "sha256": "c4c569d1e26e08008873e3a6cf2d967d72e7b782e4a7be3cb505e410f3dee395",
          "sha1": "97b140864026a09ad2a5197e69973f5c59a4b021",
          "md5": "8bee963ec21886d52ed495a6f09da0f6"
        }
      ]
    }
  ]
}
