{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-core",
    "version": "6.1.0.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-core-6.1.0.5-beta.aar",
          "url": "android-core-6.1.0.5-beta.aar",
          "size": 21993504,
          "sha512": "252c61d1659d9b03f1caf8075956307b63bd86d4fe2afec8e047960d36f1e60ee11d5184f61d1c0532fc077c848bc4735565b0accd0ebb78d786c132dc7cba18",
          "sha256": "1d5026631d385bf33864b41ce1082eadc2738cebddacc4aaf331808717f200c4",
          "sha1": "482cf5d456c30bbb9c0692724af3b8c25645795b",
          "md5": "9865b3f5c1ee70a0fa595ef76627b1cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-core-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-design",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-support-v4",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "pl.charmas.android",
          "module": "android-reactive-location2",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "nl.littlerobots.rxlint",
          "module": "rxlint",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.pubnub",
          "module": "pubnub-gson",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.45"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.16.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review-ktx",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.3.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config-ktx"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-ktx"
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.29"
          }
        },
        {
          "group": "com.appboy",
          "module": "android-sdk-ui",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.twilio",
          "module": "video-android",
          "version": {
            "requires": "7.6.4"
          }
        },
        {
          "group": "com.github.lisawray.groupie",
          "module": "groupie",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.github.lisawray.groupie",
          "module": "groupie-viewbinding",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "v3.1.0"
          }
        },
        {
          "group": "com.tomergoldst.android",
          "module": "tooltips",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.github.xabaras",
          "module": "RecyclerViewSwipeDecorator",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-services",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-common",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-utils",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-common",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "android-sdk-java",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-ui",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-models",
          "version": {
            "requires": "6.1.0.5-beta"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-core-6.1.0.5-beta.aar",
          "url": "android-core-6.1.0.5-beta.aar",
          "size": 21993504,
          "sha512": "252c61d1659d9b03f1caf8075956307b63bd86d4fe2afec8e047960d36f1e60ee11d5184f61d1c0532fc077c848bc4735565b0accd0ebb78d786c132dc7cba18",
          "sha256": "1d5026631d385bf33864b41ce1082eadc2738cebddacc4aaf331808717f200c4",
          "sha1": "482cf5d456c30bbb9c0692724af3b8c25645795b",
          "md5": "9865b3f5c1ee70a0fa595ef76627b1cb"
        }
      ]
    }
  ]
}
