{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-account-recovery-ui",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-ui-6.3.0-alpha.aar",
          "url": "feature-account-recovery-ui-6.3.0-alpha.aar",
          "size": 257145,
          "sha512": "10c0c85cccfdf984699e0d98863e30b408915bcf76425074f85fb2934d5716ac8dafa349d291d2357aac59b6c6d30fdccf9302009104c0638f8a9494f05f140b",
          "sha256": "7d397bcb166a87a78920a9b29124048d26d8c721b929c63c0bffe99409640abf",
          "sha1": "558c5ed31850466bd11ddb8ff2e4bbbfcd8fe13e",
          "md5": "5d54aa32812e1d1cfc8a34782ce8e5fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-account-recovery-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-utils",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-ui-6.3.0-alpha.aar",
          "url": "feature-account-recovery-ui-6.3.0-alpha.aar",
          "size": 257145,
          "sha512": "10c0c85cccfdf984699e0d98863e30b408915bcf76425074f85fb2934d5716ac8dafa349d291d2357aac59b6c6d30fdccf9302009104c0638f8a9494f05f140b",
          "sha256": "7d397bcb166a87a78920a9b29124048d26d8c721b929c63c0bffe99409640abf",
          "sha1": "558c5ed31850466bd11ddb8ff2e4bbbfcd8fe13e",
          "md5": "5d54aa32812e1d1cfc8a34782ce8e5fd"
        }
      ]
    }
  ]
}
