{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-labs-data",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-data-6.1.0.4-beta.aar",
          "url": "feature-labs-data-6.1.0.4-beta.aar",
          "size": 32112,
          "sha512": "5d84feb06224e2a5e253bbc74d6ed2571ff53d06df8b72d524aad696f9dce9829a6edf3dec36d83dbc41739a8ef446d594bcb9b03cf8b886e88f8dad2d94acf4",
          "sha256": "366c99b5902f5c0dfc7b048f97db0b41a3b08a357172b0c1aa83cb96e4b804fa",
          "sha1": "d8366906ff62e50cc8975da440d793ae38d50594",
          "md5": "9cc1aabcd6aa42287df44f1cf83b21d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-labs-domain",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-labs-data-6.1.0.4-beta.aar",
          "url": "feature-labs-data-6.1.0.4-beta.aar",
          "size": 32112,
          "sha512": "5d84feb06224e2a5e253bbc74d6ed2571ff53d06df8b72d524aad696f9dce9829a6edf3dec36d83dbc41739a8ef446d594bcb9b03cf8b886e88f8dad2d94acf4",
          "sha256": "366c99b5902f5c0dfc7b048f97db0b41a3b08a357172b0c1aa83cb96e4b804fa",
          "sha1": "d8366906ff62e50cc8975da440d793ae38d50594",
          "md5": "9cc1aabcd6aa42287df44f1cf83b21d2"
        }
      ]
    }
  ]
}
