{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-core-models",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.0.1.3-beta.jar",
          "url": "mdlive-core-models-6.0.1.3-beta.jar",
          "size": 159468,
          "sha512": "691962dc725084c7df988d4aa26b4029f770b218d975da76b3cfc05ebfe7967188577afb80a9e78a32707cd0c47d6b8317bb2b117eb75ba41202adc7a50bbcb0",
          "sha256": "3b515eefdb1f5869d8eb2de37c866050db2c4bc2bb613e98275b095545caf039",
          "sha1": "a3b336213c82c8da17efa43a61d65bd9569c39cf",
          "md5": "ade42f70140291572f484e7bf21d690e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-core-models-6.0.1.3-beta.jar",
          "url": "mdlive-core-models-6.0.1.3-beta.jar",
          "size": 159468,
          "sha512": "691962dc725084c7df988d4aa26b4029f770b218d975da76b3cfc05ebfe7967188577afb80a9e78a32707cd0c47d6b8317bb2b117eb75ba41202adc7a50bbcb0",
          "sha256": "3b515eefdb1f5869d8eb2de37c866050db2c4bc2bb613e98275b095545caf039",
          "sha1": "a3b336213c82c8da17efa43a61d65bd9569c39cf",
          "md5": "ade42f70140291572f484e7bf21d690e"
        }
      ]
    }
  ]
}
