{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-utils",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-utils-6.1.0.4-beta.aar",
          "url": "mdlive-utils-6.1.0.4-beta.aar",
          "size": 33389,
          "sha512": "0bcbc4a84375658098b6b00aa8525437ddf83e581d8140ecf19234785455aa68ddbbca8031bfac4f6f4577ba91da7fb46fe934c01a09be95149d1e82673d10ce",
          "sha256": "0d750069ecb46a0a51045d962565358d7340647af71da8ae093cebeedfbb54a3",
          "sha1": "23e74f1547b9b65c33989ec1bebfa6aede4943a3",
          "md5": "5b663f26f2f71fa002056e85169c4a0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-design",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-support-v4",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "nl.littlerobots.rxlint",
          "module": "rxlint",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-utils-6.1.0.4-beta.aar",
          "url": "mdlive-utils-6.1.0.4-beta.aar",
          "size": 33389,
          "sha512": "0bcbc4a84375658098b6b00aa8525437ddf83e581d8140ecf19234785455aa68ddbbca8031bfac4f6f4577ba91da7fb46fe934c01a09be95149d1e82673d10ce",
          "sha256": "0d750069ecb46a0a51045d962565358d7340647af71da8ae093cebeedfbb54a3",
          "sha1": "23e74f1547b9b65c33989ec1bebfa6aede4943a3",
          "md5": "5b663f26f2f71fa002056e85169c4a0c"
        }
      ]
    }
  ]
}
