{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-account-recovery-data",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-data-6.3.0-alpha.aar",
          "url": "feature-account-recovery-data-6.3.0-alpha.aar",
          "size": 77107,
          "sha512": "8a502eb9f1fce1882c802cdadbf40959837d407b4330bd150c93a5b236c0ef617aae8c3e1e50d77bd2353bb45c4e452637ddbb993edcc9a4eb6273c35f704137",
          "sha256": "4b35499eaee97050905acc677cd82ad435cc5f9be2678576442faabedf9a4c23",
          "sha1": "841b77cafced26859910d8db039e1168141ef045",
          "md5": "50ef46992a99481fa2da9c83ea81ec78"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-account-recovery-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-recovery-data-6.3.0-alpha.aar",
          "url": "feature-account-recovery-data-6.3.0-alpha.aar",
          "size": 77107,
          "sha512": "8a502eb9f1fce1882c802cdadbf40959837d407b4330bd150c93a5b236c0ef617aae8c3e1e50d77bd2353bb45c4e452637ddbb993edcc9a4eb6273c35f704137",
          "sha256": "4b35499eaee97050905acc677cd82ad435cc5f9be2678576442faabedf9a4c23",
          "sha1": "841b77cafced26859910d8db039e1168141ef045",
          "md5": "50ef46992a99481fa2da9c83ea81ec78"
        }
      ]
    }
  ]
}
