{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "android-sdk-java-android-sdk-java",
    "version": "6.0.1.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.0.1.3-beta.jar",
          "url": "android-sdk-java-android-sdk-java-6.0.1.3-beta.jar",
          "size": 87574,
          "sha512": "d123ad88f97571055168bcfd6bd8d08bc0a053d08cc03cc43bea23eb4756f96562106e87c8a2190e3101d8e2f8492fced6a5eb2f4ca176c775c424e0787b52ed",
          "sha256": "fab704436ff66ef2ab3c70d6884d17e0e240793fcf9f5e837c77d663faf9a6f4",
          "sha1": "5c4a15de9184b93ed73c9b361233451bed05926d",
          "md5": "b40a962e07737a5944d33d7ea2278348"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-java-android-sdk-java-6.0.1.3-beta.jar",
          "url": "android-sdk-java-android-sdk-java-6.0.1.3-beta.jar",
          "size": 87574,
          "sha512": "d123ad88f97571055168bcfd6bd8d08bc0a053d08cc03cc43bea23eb4756f96562106e87c8a2190e3101d8e2f8492fced6a5eb2f4ca176c775c424e0787b52ed",
          "sha256": "fab704436ff66ef2ab3c70d6884d17e0e240793fcf9f5e837c77d663faf9a6f4",
          "sha1": "5c4a15de9184b93ed73c9b361233451bed05926d",
          "md5": "b40a962e07737a5944d33d7ea2278348"
        }
      ]
    }
  ]
}
