{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.2-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.2-beta.jar",
          "size": 208128,
          "sha512": "9580c00f9ca4a7d5f6394dc363e81b30f2d0fa17dfdec00ceb7044a4e0ac801dea71f176d5c852e1b524770a52d3054170d4901fb4e856d517695054b6e94fcc",
          "sha256": "87bdefaa3a50cdf47220dea7ca56c71855fd0e0d290ad65c56fc7b1212fe0f29",
          "sha1": "378a7f92251c783362770c3db48b79cb6039e4af",
          "md5": "1677cbf63542e0616a1e0dcb2cda7653"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.2-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.2-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.2-beta.jar",
          "size": 208128,
          "sha512": "9580c00f9ca4a7d5f6394dc363e81b30f2d0fa17dfdec00ceb7044a4e0ac801dea71f176d5c852e1b524770a52d3054170d4901fb4e856d517695054b6e94fcc",
          "sha256": "87bdefaa3a50cdf47220dea7ca56c71855fd0e0d290ad65c56fc7b1212fe0f29",
          "sha1": "378a7f92251c783362770c3db48b79cb6039e4af",
          "md5": "1677cbf63542e0616a1e0dcb2cda7653"
        }
      ]
    }
  ]
}
