{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-data",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-data-6.3.0-alpha.aar",
          "url": "feature-data-6.3.0-alpha.aar",
          "size": 32342,
          "sha512": "8db39b2052af014a099617e37c2d7ec79deaa1ccb3f4e752d14c4fd07b5883db6017279712d1e3cb507406fb6378bb548290aa9a5d7a9bfddf8d27c62b3cc653",
          "sha256": "bbc4207fa9da10bb055d98c63ca2e7bca6c93d0f99b9c3a4e202e225c90bcc9b",
          "sha1": "21eea19474782c417196f7012762baab9e1a9a8a",
          "md5": "e86127352aa2e691f6d4c53a8bccf724"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-data-6.3.0-alpha.aar",
          "url": "feature-data-6.3.0-alpha.aar",
          "size": 32342,
          "sha512": "8db39b2052af014a099617e37c2d7ec79deaa1ccb3f4e752d14c4fd07b5883db6017279712d1e3cb507406fb6378bb548290aa9a5d7a9bfddf8d27c62b3cc653",
          "sha256": "bbc4207fa9da10bb055d98c63ca2e7bca6c93d0f99b9c3a4e202e225c90bcc9b",
          "sha1": "21eea19474782c417196f7012762baab9e1a9a8a",
          "md5": "e86127352aa2e691f6d4c53a8bccf724"
        }
      ]
    }
  ]
}
