{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.0.1.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.0.1.2-beta.jar",
          "url": "feature-dashboard-domain-6.0.1.2-beta.jar",
          "size": 153368,
          "sha512": "3119b4c29d9a14f5561ac619d3009176aa29c38acfa46aceb3569cfe12feab19d6715e9645299b62b7de63c17ae3f69e2e24f7e81abafd9d58bfb05ed654fae5",
          "sha256": "93c9b1d8a369492a81e81cc72145da3d05651cd7d879d6b9214f590764ab9600",
          "sha1": "76d308c700fd600b13c4b6233da7658742e09862",
          "md5": "7ea37a3819e716eee0b60779edacafc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.0.1.2-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.0.1.2-beta.jar",
          "url": "feature-dashboard-domain-6.0.1.2-beta.jar",
          "size": 153368,
          "sha512": "3119b4c29d9a14f5561ac619d3009176aa29c38acfa46aceb3569cfe12feab19d6715e9645299b62b7de63c17ae3f69e2e24f7e81abafd9d58bfb05ed654fae5",
          "sha256": "93c9b1d8a369492a81e81cc72145da3d05651cd7d879d6b9214f590764ab9600",
          "sha1": "76d308c700fd600b13c4b6233da7658742e09862",
          "md5": "7ea37a3819e716eee0b60779edacafc7"
        }
      ]
    }
  ]
}
