{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-template-ui",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-ui-6.3.0-alpha.aar",
          "url": "feature-template-ui-6.3.0-alpha.aar",
          "size": 4577,
          "sha512": "ee99cdf86a89d1854f2abb9a5c3b91f81c145d07a7194df2462327951a40d787da38e7a4f0380cabc09de5158f71a55ce913bf9f5b9ea7279ee113d78d0120c4",
          "sha256": "343e16892ee25321a399740e61a3899f8b80d8362d8604ed217f58d45848e5c7",
          "sha1": "90ab4e661445107dd8f1d5eb1f537cea02fd69e0",
          "md5": "977e524c3b2f0abc8d71cda6843a5a7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-template-domain",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-ui-6.3.0-alpha.aar",
          "url": "feature-template-ui-6.3.0-alpha.aar",
          "size": 4577,
          "sha512": "ee99cdf86a89d1854f2abb9a5c3b91f81c145d07a7194df2462327951a40d787da38e7a4f0380cabc09de5158f71a55ce913bf9f5b9ea7279ee113d78d0120c4",
          "sha256": "343e16892ee25321a399740e61a3899f8b80d8362d8604ed217f58d45848e5c7",
          "sha1": "90ab4e661445107dd8f1d5eb1f537cea02fd69e0",
          "md5": "977e524c3b2f0abc8d71cda6843a5a7e"
        }
      ]
    }
  ]
}
