{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-ui",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.1.0.4-beta.aar",
          "url": "mdlive-ui-6.1.0.4-beta.aar",
          "size": 3042767,
          "sha512": "d3e8e6d47a759f16f93267b65ea4585e16f240e1b8c75f6b8f0e4806396fb24706906cd51251f963dddca7a09eb4f4a420cba57f4d6dff724171cfa64544ba11",
          "sha256": "d0a5d19533af8740daed48e183b094233cfd75314dc7bffd504940579ea898f6",
          "sha1": "0ccdcc3b4b8bac8aa2843fff34a67939824205fa",
          "md5": "e840ba4f3662fa0ea48954e6bf5e30a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-ui-6.1.0.4-beta.aar",
          "url": "mdlive-ui-6.1.0.4-beta.aar",
          "size": 3042767,
          "sha512": "d3e8e6d47a759f16f93267b65ea4585e16f240e1b8c75f6b8f0e4806396fb24706906cd51251f963dddca7a09eb4f4a420cba57f4d6dff724171cfa64544ba11",
          "sha256": "d0a5d19533af8740daed48e183b094233cfd75314dc7bffd504940579ea898f6",
          "sha1": "0ccdcc3b4b8bac8aa2843fff34a67939824205fa",
          "md5": "e840ba4f3662fa0ea48954e6bf5e30a0"
        }
      ]
    }
  ]
}
