{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-models",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-models-6.3.0-alpha.jar",
          "url": "mdlive-models-6.3.0-alpha.jar",
          "size": 2551719,
          "sha512": "bee9e985a4b1519c5ed0e112f379f964bbcfb32c3ab28fcd6dff4b0db90f56860c0fa7d7fc1ceea76235682fae27e792fe85d31656e8486aba01b578b0e2763f",
          "sha256": "59a2d974cc125e2374a3b867821476857d8c6d8e0dc94e434257ff0f35ead602",
          "sha1": "3d9fc5f3788fb74c94e45ed8b9b03adefe2ac967",
          "md5": "5a5f15aeeb5e7ce542c36eb7c02e4487"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-models-6.3.0-alpha.jar",
          "url": "mdlive-models-6.3.0-alpha.jar",
          "size": 2551719,
          "sha512": "bee9e985a4b1519c5ed0e112f379f964bbcfb32c3ab28fcd6dff4b0db90f56860c0fa7d7fc1ceea76235682fae27e792fe85d31656e8486aba01b578b0e2763f",
          "sha256": "59a2d974cc125e2374a3b867821476857d8c6d8e0dc94e434257ff0f35ead602",
          "sha1": "3d9fc5f3788fb74c94e45ed8b9b03adefe2ac967",
          "md5": "5a5f15aeeb5e7ce542c36eb7c02e4487"
        }
      ]
    }
  ]
}
