{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-models",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-models-6.3.0-alpha.jar",
          "url": "mdlive-models-6.3.0-alpha.jar",
          "size": 2551719,
          "sha512": "d05143c857a80daed2963c9c05298004b171efc5a58d9a5349472d517dc729789cd3fc6811cb45c3800cc7623c0af434b9e95802306ee43a52edb1733389656f",
          "sha256": "2639e120385f56fa468f7919470d498aa3759394fbc97493d983fdd81be9e919",
          "sha1": "9ad3ffad6b61c49a06e800590fd5f010e27ca251",
          "md5": "d877b841109223064cb8106e9b037519"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.3.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.1.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-models-6.3.0-alpha.jar",
          "url": "mdlive-models-6.3.0-alpha.jar",
          "size": 2551719,
          "sha512": "d05143c857a80daed2963c9c05298004b171efc5a58d9a5349472d517dc729789cd3fc6811cb45c3800cc7623c0af434b9e95802306ee43a52edb1733389656f",
          "sha256": "2639e120385f56fa468f7919470d498aa3759394fbc97493d983fdd81be9e919",
          "sha1": "9ad3ffad6b61c49a06e800590fd5f010e27ca251",
          "md5": "d877b841109223064cb8106e9b037519"
        }
      ]
    }
  ]
}
