{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-debugmenu-data",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-data-6.1.0.4-beta.aar",
          "url": "feature-debugmenu-data-6.1.0.4-beta.aar",
          "size": 4454,
          "sha512": "c5d8c79337137b54b2eb0fde316ab48f80670e5f024b0bdd33a45bd8619c03d0060eeb4bcd66917b0d06440a68b36d644ff439142f8e7dd442374ae758d1868a",
          "sha256": "c9bd22941a06f62137bd727cd9e14787b6b3a12cc6fa3f903bbb66edb0f28f73",
          "sha1": "16f712893931acce09278a98bc81289170607e12",
          "md5": "0361ef01b5fcf053cb5843bbf36321dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.45"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-debugmenu-data-6.1.0.4-beta.aar",
          "url": "feature-debugmenu-data-6.1.0.4-beta.aar",
          "size": 4454,
          "sha512": "c5d8c79337137b54b2eb0fde316ab48f80670e5f024b0bdd33a45bd8619c03d0060eeb4bcd66917b0d06440a68b36d644ff439142f8e7dd442374ae758d1868a",
          "sha256": "c9bd22941a06f62137bd727cd9e14787b6b3a12cc6fa3f903bbb66edb0f28f73",
          "sha1": "16f712893931acce09278a98bc81289170607e12",
          "md5": "0361ef01b5fcf053cb5843bbf36321dd"
        }
      ]
    }
  ]
}
