{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-utils",
    "version": "6.3.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-utils-6.3.0-alpha.aar",
          "url": "mdlive-utils-6.3.0-alpha.aar",
          "size": 45436,
          "sha512": "383210603b057e14f1815e4d3f507421bc627505892ec8a44127790f006c2bf33ca46fa1fa5fd271584d0872bdf274720c9f13da5828e6a503e9cd0abce64f64",
          "sha256": "23d46dda1f375977daa853c2825a5f221b53edb5dbc28ff41da500b291e1a20e",
          "sha1": "0f4f4ee5c350da5775091e455dc8f967a7f933d6",
          "md5": "b91c21b653224b83b6d71304b6c9a4c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-design",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-support-v4",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "nl.littlerobots.rxlint",
          "module": "rxlint",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-utils-6.3.0-alpha.aar",
          "url": "mdlive-utils-6.3.0-alpha.aar",
          "size": 45436,
          "sha512": "383210603b057e14f1815e4d3f507421bc627505892ec8a44127790f006c2bf33ca46fa1fa5fd271584d0872bdf274720c9f13da5828e6a503e9cd0abce64f64",
          "sha256": "23d46dda1f375977daa853c2825a5f221b53edb5dbc28ff41da500b291e1a20e",
          "sha1": "0f4f4ee5c350da5775091e455dc8f967a7f933d6",
          "md5": "b91c21b653224b83b6d71304b6c9a4c5"
        }
      ]
    }
  ]
}
