{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-domain",
    "version": "6.1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.4-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.4-beta.jar",
          "size": 208080,
          "sha512": "81d00de32e8abc88b947cad85c46565300ba4e43fefb783230f7634d623f76c1b0588c1027234a5d2ecdd5349accd043a1608299df05551084b8658cf180a8a5",
          "sha256": "86a59f1558eb465e6c06c3358784f483cd0bd3f38826970f18b8c3f7f045d1d0",
          "sha1": "c86b1bd4308bb6362329f9d4075c343f9f40237a",
          "md5": "56cdc20fcddddac5009e1e2093f2873b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "feature-debugmenu-domain",
          "version": {
            "requires": "6.1.0.4-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-domain-6.1.0.4-beta.jar",
          "url": "feature-dashboard-domain-6.1.0.4-beta.jar",
          "size": 208080,
          "sha512": "81d00de32e8abc88b947cad85c46565300ba4e43fefb783230f7634d623f76c1b0588c1027234a5d2ecdd5349accd043a1608299df05551084b8658cf180a8a5",
          "sha256": "86a59f1558eb465e6c06c3358784f483cd0bd3f38826970f18b8c3f7f045d1d0",
          "sha1": "c86b1bd4308bb6362329f9d4075c343f9f40237a",
          "md5": "56cdc20fcddddac5009e1e2093f2873b"
        }
      ]
    }
  ]
}
