{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-utils",
    "version": "6.1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-utils-6.1.0.1-beta.aar",
          "url": "mdlive-utils-6.1.0.1-beta.aar",
          "size": 33223,
          "sha512": "a38acc704b7216b8448a85d97de6d5f3d3b7dc93accf7325851c9c6aa40263430775cb972fbc7f2dbd6b1fa0774ae92bd2e55fe90d932f7c66332c5820c6cea4",
          "sha256": "e6ae3965b5349759a7aac7b7e322d7da57ea1e077a0551dc2ae4a0ca3293bb20",
          "sha1": "74e6722c6787c2eace7534da13ec9e3993992f27",
          "md5": "a0859f63bbde2901bbe1bc956ae6b819"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-design",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-support-v4",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "nl.littlerobots.rxlint",
          "module": "rxlint",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-utils-6.1.0.1-beta.aar",
          "url": "mdlive-utils-6.1.0.1-beta.aar",
          "size": 33223,
          "sha512": "a38acc704b7216b8448a85d97de6d5f3d3b7dc93accf7325851c9c6aa40263430775cb972fbc7f2dbd6b1fa0774ae92bd2e55fe90d932f7c66332c5820c6cea4",
          "sha256": "e6ae3965b5349759a7aac7b7e322d7da57ea1e077a0551dc2ae4a0ca3293bb20",
          "sha1": "74e6722c6787c2eace7534da13ec9e3993992f27",
          "md5": "a0859f63bbde2901bbe1bc956ae6b819"
        }
      ]
    }
  ]
}
