{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "mdlive-common",
    "version": "6.0.1.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mdlive-common-6.0.1.2-beta.jar",
          "url": "mdlive-common-6.0.1.2-beta.jar",
          "size": 15516,
          "sha512": "f4f1ef9a85730507662c8a2477074bbb2936b9e2baf44f50473c188c918c7ed8ab5e4be9caf9f95e020327155bedf5fa746ea3d75c0644ffed61411666b75735",
          "sha256": "82536323e623b3f5dbca6db610f4aec14e3fcba0458ee0a0f1b7d61d0fdcc693",
          "sha1": "0eae244f0f34a881d950b78268e8c16dbedb45d6",
          "md5": "b321a07bd986d34a5c0c3717400f73cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "mdlive-common-6.0.1.2-beta.jar",
          "url": "mdlive-common-6.0.1.2-beta.jar",
          "size": 15516,
          "sha512": "f4f1ef9a85730507662c8a2477074bbb2936b9e2baf44f50473c188c918c7ed8ab5e4be9caf9f95e020327155bedf5fa746ea3d75c0644ffed61411666b75735",
          "sha256": "82536323e623b3f5dbca6db610f4aec14e3fcba0458ee0a0f1b7d61d0fdcc693",
          "sha1": "0eae244f0f34a881d950b78268e8c16dbedb45d6",
          "md5": "b321a07bd986d34a5c0c3717400f73cc"
        }
      ]
    }
  ]
}
