{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mdlive.mdla",
    "module": "feature-dashboard-ui",
    "version": "6.1.0.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-ui-6.1.0.0-beta.aar",
          "url": "feature-dashboard-ui-6.1.0.0-beta.aar",
          "size": 1542271,
          "sha512": "85a2895d2ecb9386456598e9ddf7ca0b299f784472134fc0cfd744d3caba0bced7a9526617554d059f9efd4006d8779aeec682ca7045f32bf1bc03c56f4a1f7c",
          "sha256": "b5d6a565256dc381245c1424a6e8b5e2c5224bcdabc8d608506415a7ca1fefb7",
          "sha1": "4def2f5b0fb17a06c7bed564bad1d1ace9a61b0c",
          "md5": "fb40ac68e3d894f5cfa8b93298e60faf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mdlive.mdla",
          "module": "feature-dashboard-domain",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-ui",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "com.mdlive.mdla",
          "module": "mdlive-core-models",
          "version": {
            "requires": "6.1.0.0-beta"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "feature-dashboard-ui-6.1.0.0-beta.aar",
          "url": "feature-dashboard-ui-6.1.0.0-beta.aar",
          "size": 1542271,
          "sha512": "85a2895d2ecb9386456598e9ddf7ca0b299f784472134fc0cfd744d3caba0bced7a9526617554d059f9efd4006d8779aeec682ca7045f32bf1bc03c56f4a1f7c",
          "sha256": "b5d6a565256dc381245c1424a6e8b5e2c5224bcdabc8d608506415a7ca1fefb7",
          "sha1": "4def2f5b0fb17a06c7bed564bad1d1ace9a61b0c",
          "md5": "fb40ac68e3d894f5cfa8b93298e60faf"
        }
      ]
    }
  ]
}
